### ISSUE TITLE
Feature request: Add TexTools to Windows WinGet Repository

### ISSUE THREAD

**Issue by TheOddball** [TexTools/FFXIV_TexTools_UI#100]
https://github.com/microsoft/winget-pkgs this would be an excellent addition for power users! Thank you <3

**Comment by Squall-Leonhart** [comment]
thats not gunna happen.

microsoft require any software distributed through affiliate channels to be code signed with a sha256 certificate.

**Comment by ZForceSeattle** [comment]
> thats not gunna happen.
> 
> microsoft require any software distributed through affiliate channels to be code signed with a sha256 certificate.

Just to give weight to Squall's response... it's not worth going through Microsoft/Windows. As a former contractor as well as an producer of content and programs as a 3rd party it does not give any benefit to the end user or the programmer to go through that process. Not only is it a time commitment but it is a pain in the neck to get it done.

**Comment by KoraLyn** [comment]
Yea, this is probably not going to happen. Appreciate the suggestion though!
