### ISSUE TITLE
Random Crashes When Installed Mods Using TexTools

### ISSUE THREAD

**Issue by tigurand** [TexTools/FFXIV_TexTools_UI#103]
I don't know if it's because I have too many mods, but my FF often crashed randomly, without error message. Usually it happened when I just entered duty, or when I stay at crowded city.

I checked for error, but it shows all green. The game crashed even if I disable all mods, but it's stable when I do start over.

In my desperate effort to use mods, I installed all mods using Penumbra, and I don't have any crashes anymore. The mods are the same one I installed with TexTools before, so I guess what causes crash is not any particular mod, but maybe something with how TexTools tamper the game files.

**Comment by Squall-Leonhart** [comment]
not a textools bug

**Comment by KoraLyn** [comment]
These kinds of issues are definitely still present but also extremely hard to reproduce and therefore fix. Keeping your modlist clean by doing a start-over every now and then and not just constantly installing more and more mods across multiple patches generally prevents these issues from happening.
