### ISSUE TITLE
Feature Request: Allow organising of mod packs in to directories

### ISSUE THREAD

**Issue by Riiskyy** [TexTools/FFXIV_TexTools_UI#104]
Currently when going in to the menu to manage installed modpacks, all currently installed modpacks appear in a single list under the 'Modpacks' tree.

It would be nice if we were able to organise this further by creating our own directories under modpacks. For example letting users create a structure like
```
Modpacks > UI
Modpacks > Clothing
Modpacks > Weapon mods
Modpacks > Skinmods
```

This would make going navigating and enabling/disabling currently installed modpacks a lot easier for users who might have many modpacks installed.

I'm not sure if this is feasible or if many others would want it but it would be a nice QoL feature for those who like to keep things organised and easy to find.

**Comment by Squall-Leonhart** [comment]
This is why explorer.exe exists, make use of it.

**Comment by Riiskyy** [comment]
so the solution is to just uninstall and re-install mods every time. Can't just leave them installed and have some form of organisation?

I have them organised in explorer. I was just asking about having some form of organization in the installed modpack list

**Comment by KoraLyn** [comment]
It would be nice to have more control over the mod list but it would require quite an extensive rewrite. It's definitely on the list of possible improvements but I can't give any promises on if or when this will be improved.

**Comment by Lunaretic** [comment]
Better tools (Ex Penumbra) exist for being mod-loaders.  This is a will-not-fix at this point.  TexTools is primarily a mod creation tool with a side of being a modloader for those who don't want to use Penumbra.
