### ISSUE TITLE
Bug - Import painting option not working

### ISSUE THREAD

**Issue by Venat333** [TexTools/FFXIV_TexTools_UI#105]
Importing .png in any housing/painting cuts the .png image in halve.

Also housing/painting isn't housing picture images. Its the UI images for sightseeing. Replacing those images doesn't change the housing pictures.

**Comment by Venat333** [comment]
Bugged out version:

![bug](https://user-images.githubusercontent.com/88667593/142726074-04da1f9f-ab30-4c30-b973-f5db45fb9747.PNG)

Normal version:

![bug2](https://user-images.githubusercontent.com/88667593/142726086-9e791307-5972-41ca-9039-0f570b8fdba3.PNG)

**Comment by KoraLyn** [comment]
Seems to happen with any format, not just PNG.

**Comment by Squall-Leonhart** [comment]
The image imports correctly when it has been processed by another DDS handler (ie, Gimp) and the image has mipmaps.

**Comment by Lunaretic** [comment]
This issue has been fixed, was caused by https://github.com/TexTools/xivModdingFramework/issues/51
(The data loss at least)

The paintings not being the in-game ones is noted, but not sure where those tex files would live either to add them to the UI list.
