### ISSUE TITLE
Unable to find Role Actions under UI Actions

### ISSUE THREAD

**Issue by NaesKun** [TexTools/FFXIV_TexTools_UI#107]
Title. Role actions such as Rampart or Esuna are not on the list of skill icons under UI that's available for edit. Is there an explanation of why this is occurring?

**Comment by Squall-Leonhart** [comment]
Esuna and Rampart are listed just fine,

**Comment by NaesKun** [comment]
I don't see them in my TexTools. All I see are the older ARR that aren't the same as the ones currently used in the game.

**Comment by Squall-Leonhart** [comment]
oh, its this bug again.

**Comment by NaesKun** [comment]
Wait its a bug?!?! 

I'm curious, in the past what caused this bug to occur?

**Comment by Squall-Leonhart** [comment]
The main list filters duplicate names,

as a workaround you can access the current forms of icons by searching for them by name

![image](https://user-images.githubusercontent.com/1098176/144727257-d0a71032-3ce7-4eb6-adb7-94635350f978.png)

**Comment by NaesKun** [comment]
Found it, thank you!
