### ISSUE TITLE
Bug Report: Rings and Bracelet accessories no longer show after disabling 'BodyShowHand' on the Body(top)'s Metadata

### ISSUE THREAD

**Issue by CordeliaMist** [TexTools/FFXIV_TexTools_UI#108]
Hello, I have been making mods on Textools for awhile now and noticed an issue that seems to have popped up out of nowhere.

In previous mods I have made in the past, such as my straitjacket mod, and full body hemp rope mod, they have all made use of disabling the 'BodyShowHand' box in the top's Metadata, allowing the hands to be hidden and for the armature to be altered. Despite this, the ring and bracelet accessories would still display even though the BodyShowHand metadata option was unchecked, as you can see in the below attachments.

![1 5](https://user-images.githubusercontent.com/64883480/142956025-1ca3863e-cee4-4870-9fd8-2ed5d5572901.png)
![1](https://user-images.githubusercontent.com/64883480/142956027-2f3ba7ba-818f-4f96-92f0-c1398d44f9bb.png)

In these Attachments, you can see the straitjacket mod I had made before this issue popped up. The BodyShowHand box was unchecked, and the accessories showed regardless. You can also see this in another mod I had made before the issue showed up, in my armbinder mod.

![2 5](https://user-images.githubusercontent.com/64883480/142956107-ea0f8b2d-f4a7-4d69-940f-32efd161df7a.png)
![2](https://user-images.githubusercontent.com/64883480/142956109-19ce822e-7abc-4749-bc3e-db6b10a19590.png)
--------------------
You can see once again, that this feature used to work. However, as of lately, when I attempt to change the metadata in my newer mods by disabling BodyShowHand, the ring and bracelet accessories will vanish entirely. (As you can see below in my latest mod) 
![3 5](https://user-images.githubusercontent.com/64883480/142956263-3a44bf0e-8441-4c28-8e9c-0c5be7434a6d.png)
![3](https://user-images.githubusercontent.com/64883480/142956265-d4da60e7-0ff4-4378-98c6-df4473f872d7.png)

![4 5](https://user-images.githubusercontent.com/64883480/142956275-28dc4b07-504a-42be-8537-58eaec035011.png)
![4](https://user-images.githubusercontent.com/64883480/142956276-f69a5b90-e0b9-4d26-9d86-7ced7e28ccc7.png)
Even with the latex armbinder, I practically have copied over the settings from the new world jacket on the metadata and model over to that top, but it would not work regardless of what I tried. However, once the BodyShowHand was checked, as seen on the normal latex top, they will magically appear again.

This only happens with any model I try to change the metadata of after the latex model I posted, which was on 10/24/21, and every additional model past this date I have tried to modify the metadata of produce the same results.

I am not sure if this is only an issue on my end, as others have tested it and seen the same results.
To answer the question about penumbra, I only used penumbra as a external source to see if there was any difference between the ones that worked and ones that did not. This hypothesis did seem true as the ones with the issues had working metadata manipulation, and the ones without the issue did not have working metadata manipulation on penumbra.
To clarify another point about penumbra, no i did not only put these into penumbra, this issues pop up as well when plugging the mods into just textools and removing them off penumbra you will get the same result.

Another side mention I happened to notice was that the bone armature for the arms in my save files on my PC show the full body armature, however once I import the model into textools and export the file back out of textools once it shows the issue, the armature bones for the arms vanish from the model, only containing the bones for the main body, which is odd, but may or may not be connected to the issue.

I personally think that this issue happened from a patch or update in textools, as I have tried looking into many different possibilities and asking around but nobody can seem to find the answer, so I have reasonable claim it may be something on the side of textools and not me. However if this is just an issue on my end, or a step I skipped over, I would be glad to know what I missed. As I did not do much different on any new models compared to the ones that already work.

Thank you for paying attention to this bug in advance, it means a lot.

**Comment by Squall-Leonhart** [comment]
This is behavior changed by Square Enix in 5.18, this metadata now hides rings.

> An issue wherein the graphics of equipment obtained from the alliance raid the Copied Factory did not display correctly.
> * As a result of addressing this issue, certain equipment for the hands that appear as bracelets will now display. However, certain equipment that appears as rings will no longer display.

**Comment by CordeliaMist** [comment]
If this behavior was changed by Square Enix, then why does it still work on previously made mods?

**Comment by OasisAnimos** [comment]
Further more, this bug only occured after 5.58, so why you say this is making no sense to me. This only began happening after 10/16-24/2021

**Comment by CordeliaMist** [comment]
> This is behavior changed by Square Enix in 5.18, this metadata now hides rings.
> 
> > An issue wherein the graphics of equipment obtained from the alliance raid the Copied Factory did not display correctly.
> > 
> > * As a result of addressing this issue, certain equipment for the hands that appear as bracelets will now display. However, certain equipment that appears as rings will no longer display.

 This bug only occurred at some point after after 5.58 or later, so why you say this relates to this issue does not make sense, because Mods I have made after 5.18 did work up to this point in time. This only began happening after 10/16-24/2021
On top of this, if what you are saying about is true, it makes no logical sense either for the issue reported. Your reference mentions that as a result of addressing the issue, certain equipment for the hands that appear as bracelets will now display. **However, certain equipment that appears as rings will no longer display** But this is not the same kind of issue presented in the report above

I strongly believe that the source of this issue is in Textools itself. It has worked in the past, and no longer does.
**I took much time to provide as much evidence, details, and information needed in this report, please do not judge the issue by the title alone, I would hope this could be resolved or identified with the information provided. Thank you**

**Comment by CordeliaMist** [comment]
I have found the solution to this issue after looking into it with other modders. The reason the bodyshowhand was hiding the accessories was due to after a certain update, or just simply on certain items, when the hands are hidden, the metadata of that set item, which you have to look up its ID set number in order to even find the sets gloves which are not tagged with a name and simply a number, and the metadata of this item takes precidence over the visability when the hands are hidden. So there was no change in 5.18 that altered this, it is simply a hidden metadata for the set in the setting in textools that others I brought the issue up to were unable to point out. I have figured it out however, for anyone else dealing with this issue, that is the fix
