### ISSUE TITLE
when i open the program，show me this message“install directory not found”

### ISSUE THREAD

**Issue by SoftSlime** [TexTools/FFXIV_TexTools_UI#112]
just like this
![捕获](https://user-images.githubusercontent.com/95559412/144735283-b111bfb4-85db-4a97-92d9-f1711fdc353e.PNG)
my friend suggest me use english path,It didn't work.
current version not support chinese server？

**Comment by Squall-Leonhart** [comment]
it supports chinese just fine, scroll the message and follow the directions.
