### ISSUE TITLE
Viera Female hair #18 not showing in textools

### ISSUE THREAD

**Issue by KariWasHere** [TexTools/FFXIV_TexTools_UI#114]
Textools only shows 17 hairs for Viera females even though there is 18 in my game, there is one more after the viera hair that has the headpiece in my game. I have a mod that is making that last hair texture look odd and was going to try manually disabling the texture maps on that specific hair but I cannot since the viera fem hairs only go up to number 17. I am on the latest update for textools endwalker 2.3.7
![Screenshot_1](https://user-images.githubusercontent.com/95600247/144782043-f8d73ec0-8b61-4173-8da9-4cdc027d4ec6.png)
.

**Comment by Squall-Leonhart** [comment]
The hair style selected is shared with all races and the textures can be found on midlander female. (Goes for all hairs with a triple digit model number)

![image](https://user-images.githubusercontent.com/1098176/144812509-fa27dc22-1e77-43e8-a136-dbe1d64156fd.png)

**Comment by KariWasHere** [comment]
thank you!
