### ISSUE TITLE
[Severity:Dataloss] Textools doesn't prevent users from configuring backups to the same folder as modpacks and saved exports.

### ISSUE THREAD

**Issue by Squall-Leonhart** [TexTools/FFXIV_TexTools_UI#116]
When the index downloader is invoked it purges the folder of all existing files, this will result in the loss of non-index content in the folder with no ability to retrieve from the recycle bin.

**Comment by Lunaretic** [comment]
Fixed in latest version/Dawntrail builds.

**Comment by Lunaretic** [comment]
(Accidentally closed wrong issue)

**Comment by Lunaretic** [comment]
Resolved now.  TT will explicitly throw an error if the Backup folder has files other than indexes & the game version file in it.
