### ISSUE TITLE
New 6.0 variants not copying colorset changes

### ISSUE THREAD

**Issue by FaithOriginalisme** [TexTools/FFXIV_TexTools_UI#117]
Exaclty what is says. When attempting to edit the colorset of wind silk coattee, the colorset didn't transfer over to Scarlet Moko Coatee

**Comment by CordeliaMist** [comment]
This is how Variants are meant to work. Variants are reskinned/recolored through the use from colorsets. Modifying one colorset won’t change the others, you must download your colorset file and paste it onto the variants colorset files manually, there is no sync option, if they would all use the same colorset and share the same maps and models they wouldn’t be defined as a variant by default

**Comment by FaithOriginalisme** [comment]
All the other variants changed when I changed one,  and not scarlet moko.
The new item was the only one that didn't change. So one way or another,
something isn't working as intended.  I don't mind manually editing just
the one

**Comment by CordeliaMist** [comment]
Ah if it is  new variant custom to the new expansion then yes you will need to manually add its variant

**Comment by FaithOriginalisme** [comment]
Cool, thanks!

**Comment by KoraLyn** [comment]
As explained, this is simply how it works. Variants usually have a unique colourset so any changes only affect that specific variant.
