### ISSUE TITLE
MateriaUI buggy even after uninstall

### ISSUE THREAD

**Issue by Kellerman51** [TexTools/FFXIV_TexTools_UI#120]
This program did not work properly and after I uninstalled it and deleted all folders, I still have pixel bugs in-game :(

**Comment by Squall-Leonhart** [comment]
Sometimes not all aspects of a mod can be disabled or managed via the Mod manager UI, they can only be removed by Starting over.

That is not the case in this scenario, you would appear to have not started over prior to 6.0 so your indexes and 060000.dat3 are likely dirty.
