### ISSUE TITLE
Unable to import larger mod properly

### ISSUE THREAD

**Issue by Tutankhamena** [TexTools/FFXIV_TexTools_UI#121]
When I import a large module package (about 2.0 GB)，The page keeps showing loading and the loaded item is 0
Like this：
![image](https://user-images.githubusercontent.com/95991266/145698687-83933053-e138-456d-8f48-cf9a4332bd69.png)

**Comment by Tutankhamena** [comment]
I’m sorry if you can’t understand，Because I used a translation software, it may not mean what I say

**Comment by Squall-Leonhart** [comment]
the package is corrupt

**Comment by KoraLyn** [comment]
Either your modpack got corrupted somehow or a different error occurred while trying to unpack it to your temp folder. Feel free to reopen if you can consistently reproduce this and can give the steps to.
