### ISSUE TITLE
Error importing mods.

### ISSUE THREAD

**Issue by Seltti** [TexTools/FFXIV_TexTools_UI#122]
![20211212113815](https://user-images.githubusercontent.com/95991963/145699631-722b6733-4c69-41db-8211-0ff802ecdf5c.png)
I'm using the CN verison of the game and this pops up everytime i try to import mods. is it related to the male viera issue or is there something else i could do to fix this.

**Comment by caelum103** [comment]
Try roll back or reinstall to the previous edition, works for me.

**Comment by caelum103** [comment]
FYI I'm using 2.3.6.2

**Comment by Seltti** [comment]
> FYI I'm using 2.3.6.2

thanks for the help! Rolled back to 2.3.7, most of them works fine now except those I believe released after Endwalker went online. :( maybe I'll just wait til next tt update.

**Comment by NMDWSMAA** [comment]
sorry does anyone know how to download old version of textools?

**Comment by KoraLyn** [comment]
Please see https://github.com/TexTools/FFXIV_TexTools_UI/issues/134.
