### ISSUE TITLE
Error Importing Mods

### ISSUE THREAD

**Issue by JasonBourne33** [TexTools/FFXIV_TexTools_UI#123]
---------------------------
Error Importing Mods
---------------------------
There were errors importing some mods.

An error occured when attempting to expand the metadata entries.

Error:Could not find offset for chara/xls/charadb/equipmentdeformerparameter/c1701.eqdp
---------------------------
OK   
---------------------------
![image](https://user-images.githubusercontent.com/18242586/145828992-e20742c9-c643-4c09-8081-5672f19416c8.png)

**Comment by 1431650603** [comment]
I had the same problem, use the older vision textools.

**Comment by KoraLyn** [comment]
Please see https://github.com/TexTools/FFXIV_TexTools_UI/issues/134.
