### ISSUE TITLE
Error Importing Mods

### ISSUE THREAD

**Issue by yucv078** [TexTools/FFXIV_TexTools_UI#125]
There were errors importing some mods.

An error occured when attempting to expand the metadata entries.

Error:Could not find offset for chara/xls/charadb/equipmentdeformerparameter/c1701.eqdp

I am CN server user.I rolled back to 2.3.6.2 and 2.3.7.0 still can't install some mods,Please help me.

![QQ图片20211214221448](https://user-images.githubusercontent.com/25398211/146312529-02533e81-cd81-4f1c-b2fc-75a38cc2ca50.png)

![QQ图片20211216131702](https://user-images.githubusercontent.com/25398211/146312550-d57e8200-7052-4678-b831-60fd4e69efaa.png)

**Comment by cc11007** [comment]
哥们，问题解决了吗？解决的话也教教咱吧

**Comment by KoraLyn** [comment]
Please see https://github.com/TexTools/FFXIV_TexTools_UI/issues/137.

**Comment by Squall-Leonhart** [comment]
134 is a seperate issue (that even Int client gets), you meant 137 i bet.

**Comment by KoraLyn** [comment]
Oh yep, fixed the link. Thanks!
