### ISSUE TITLE
Install Directory Out Of Date

### ISSUE THREAD

**Issue by spotlessthoughful** [TexTools/FFXIV_TexTools_UI#126]
After initial install, opening the application and locating /FINAL FANTASY XIV - A Realm Reborn/game/sqpack/fxiv.
The following error pops up (even after selecting the correct directory)

![InstallDirectoryOutOfDate](https://user-images.githubusercontent.com/42855052/146625776-948dd0af-fbfe-475a-b0f0-2d2fee371a66.PNG)

**Comment by KoraLyn** [comment]
The appliction checks the last modified date of your game files and if it's before 2021 it throws that error so you were probably pointing it at an old secondary install you had on your system.
