### ISSUE TITLE
Error with TexTools and XIVLauncher

### ISSUE THREAD

**Issue by Kommish** [TexTools/FFXIV_TexTools_UI#128]
I am using TexTools and XIV Launcher and I keep getting this error. Is there a fix for this or am I doing something wrong with the install of TexTools? Thanks for your time!
![Launcher Error](https://user-images.githubusercontent.com/96451824/146848622-7835d24e-3c5b-4279-9813-aed6a3d3a3f4.png)

**Comment by Squall-Leonhart** [comment]
please use the discord for support queries.
