### ISSUE TITLE
How can I solve the error?

### ISSUE THREAD

**Issue by goofy1113** [TexTools/FFXIV_TexTools_UI#131]
---------------------------
Error Importing Mods
---------------------------
There were errors importing some mods.

An error occured when attempting to expand the metadata entries.

Error:Could not find offset for chara/xls/charadb/equipmentdeformerparameter/c1701.eqdp
---------------------------
OK   
---------------------------

And 

**I can't see the category list.**

A few files make that error.

**Comment by lheluox** [comment]
I also have this error

**Comment by Hyousa** [comment]
我也是

**Comment by Hyousa** [comment]
我也是

**Comment by KoraLyn** [comment]
Please see https://github.com/TexTools/FFXIV_TexTools_UI/issues/137.
