### ISSUE TITLE
Advanced MP creation, Missing Viera 101-104

### ISSUE THREAD

**Issue by Kylie-Digital** [TexTools/FFXIV_TexTools_UI#134]
When creating an advanced mod pack, The directory options for Veena's 101-104 for Viera are missing despite having files enabled. 
This happens for BOTH Male & Female Viera.

![TTMVeenaError](https://user-images.githubusercontent.com/94972334/148938185-13db21ee-70ed-4624-bfcc-fcc876db7edb.png)

**Comment by Squall-Leonhart** [comment]
Now affecting male Elezen 221 and 222. male Aura face 202, and Midlander female face 223

**Comment by FairlyIncognito** [comment]
Anyone working on a fix for this issue?

**Comment by caiyenne** [comment]
Is this being worked on?

**Comment by Lunaretic** [comment]
Resolved in latest version/Dawntrail builds.
