### ISSUE TITLE
Bug - When importing .fbx face model data Shape Keys are not applied correctly. 

### ISSUE THREAD

**Issue by KazTheKeel** [TexTools/FFXIV_TexTools_UI#142]
When importing .fbx face model data Shape Keys are not applied correctly.  The sculpt will not display correctly in-game. This bug also affects previews in the model tab, where Textools fails to apply more than one deformation shape to the imported model.

Reproduction steps with attached file: [TextoolsBugTest.zip](https://github.com/TexTools/FFXIV_TexTools_UI/files/7975637/TextoolsBugTest.zip)
1) Open file in blender.
2) Export file to .fbx  with these settings. (I have tested importing it with and without the "apply modifiers" setting, it seems to make no difference.
![image](https://user-images.githubusercontent.com/98791076/151907902-80f465e1-c506-4b3c-a451-1b8fc3fe7642.png)
3) Import the .fbx file to Elezen Female face 4 and attempt to apply deformation shapes. When using more than one the preview should reset. (Looking at the ears is an easy way to tell.)
4) Opening the file in-game should display a very different preview from the one viewed on blender or Textools.
![image](https://user-images.githubusercontent.com/98791076/151909081-c57304f6-466b-463e-999b-689858bb21f2.png)

Known workarounds:
1) Delete all Shape Keys in blender before importing and use the face options that do not apply deformation (ie: "default 0"). This will display the sculpt correctly in-game.
2) Split each area affected by a Shape Key into an individual object within blender.

The second workaround makes me believe this might be related to having more than one Shape Key deformation applied to the same object at a time.

Currently this bug makes it difficult to create face sculpts that work with a character's customization. Fixing it would allow the character to still look unique for others that don't have the mod installed. I have spoken with a few modders to investigate the issue, and it seems to be a TexTools bug rather than one created by user error.

**Comment by KoraLyn** [comment]
Can you be a bit more specific as to what the issue is? It all seems fine from what I can tell. What shape exactly isn't being applied properly?

**Comment by KazTheKeel** [comment]
> Can you be a bit more specific as to what the issue is? It all seems fine from what I can tell. What shape exactly isn't being applied properly?

The expected result would be having the [In-game preview with deformations] on appear as it does in the [blender review], but it looks very different.

In theory, if you sculpted the face in blender on the "basis" while having specific Shape Keys on you could create a face that say, only looks as desired if you use Eyes 3, Jaw 4 and Ears 3, but that creates a look different from the blender preview.

The idea is to allow for characters to look unique while unmodded, as currently you'd need to select the default options to have any face mods appear exactly as how they're sculpted (ie: no face options that use deformations, so option "0" or the first one that shows in every list during character creation).

I hope this explanation helps, I've spoken with other modders that would love to have this fixed~ Let me know if you need more information.

**Comment by Lunaretic** [comment]
The way morph data is handled is very specific and not particularly flexible.  If you have multiple morph shape categories which affect the same vertices you're going to get undefined/broken results.   In short, you must define each 'group' of vertices to only be affected by a single morph shape category.  All other vertices must remain identical to the base version.  This is likely why your Fix-2 works for you, as you're forcefully ensuring that the other vertices cannot be accidentally affected by manipulations you're doing to the morph parts.

Additionally, exporting morph data from different 3d applications can be a bit finnicky, so I would suggest re-importing the file into your 3d application after to ensure all the morph shapes are correctly included in the FBX file as desired.
