### ISSUE TITLE
An error occurs when loading certain items.

### ISSUE THREAD

**Issue by BeautifulH4rry** [TexTools/FFXIV_TexTools_UI#149]
What I've tried.
・Reinstall TexTools.
・Run "Check For Problems" > No problem.
・Run "Scan for new item Sets"
・Add the following code to Config
`<gcAllowVeryLargeObjects enabled="true" />`

I tried the above, but it did not read.

ItemID:Monster>m0124>Body>b0001>m0124b0003_v0

![0a083749c9191eadc42b3e336575e75f](https://user-images.githubusercontent.com/77454746/155037525-96828fe8-fe46-4212-8725-c6d2f3892000.png)

**Comment by Squall-Leonhart** [comment]
This model was obfuscated by the game developers to prevent data mining, several bytes that were required to load it in game were supplied only within the duty.

The model has since been unobfuscated.
