### ISSUE TITLE
Unable to created Advanced Modpacks

### ISSUE THREAD

**Issue by smilecity** [TexTools/FFXIV_TexTools_UI#153]
Been experiencing an issue wherein the Advanced Modpack option does not allow to pick category drop downs further than races. (IE. Hair numbers, face numbers, etc.)

![image](https://user-images.githubusercontent.com/100810260/156466938-d91e9619-44d2-46f2-84ca-6ccd3243d824.png)
![image](https://user-images.githubusercontent.com/100810260/156467018-9f8eaedb-b6b4-4b2a-858b-1c182f49cfc4.png)

**Comment by Squall-Leonhart** [comment]
This seems to involve either an outdated item set or bad cached data, or both, assistance for it can be had on the discord.
