### ISSUE TITLE
Import raw files bug

### ISSUE THREAD

**Issue by SageU** [TexTools/FFXIV_TexTools_UI#155]
Hello, I'm trying to import some files into the game. When I import files into the package stored in the ffxiv folder, the import function works perfectly.

However, when I import files into the package stored in the ex1, ex2, ex3 and ex4 folders, the import function puts the files under the ffxiv folder and modifies the index file under the ffxiv folder. The files under the ex folder have not changed, and the imported files have not taken effect after I enter the game.

Is this a bug in the program or a mistake in my operation? If it is my mistake, how can I operate correctly?

`cut/ex3/sound/voicem/voiceman_05300/vo_voiceman_05300_005660_m_en.scd` this is the path of the file I tried to import into the game.

**Comment by Lunaretic** [comment]
ex# folder imports/exports are not currently supported by TexTools.  This may get fixed at some point in the future, but ETA is unknown. (It's unfortunately not a trivial change)

**Comment by SageU** [comment]
> 

Thank you for your reply

Looking forward to the update support in the feature！

**Comment by Lunaretic** [comment]
This should be more doable now with the current batch of updates for Dawntrail fixing most of the cruft preventing this.

**Comment by Lunaretic** [comment]
I'm happy to say this ancient issue is finally resolved.  Starting with the Dawntrail builds Textools will be able to read/write to the expansion DATs properly.
