### ISSUE TITLE
[Feature Request] Show how much space current mods are taking up

### ISSUE THREAD

**Issue by Kussie** [TexTools/FFXIV_TexTools_UI#16]
Given we have a "soft limit" of mods, and TexTools shows an error when you attempt to go beyond this limit.   It might be nice to show the current space taken up mods versus the current soft limit to make easy to see how much space we have left for mods when installing.

**Comment by Lunaretic** [comment]
The "Soft Limit" is now 96 GB, and the application has functionality to recover unused space, so this issue is moot.
