### ISSUE TITLE
Unable to upload textures

### ISSUE THREAD

**Issue by Vampnekosama** [TexTools/FFXIV_TexTools_UI#165]
Hello, 
Ever since the last patch, I've been unable to upload any eye png or dds files in any face on TT. I can do the face uploads, just nothing else to catchlights, normals, etc. I've tried a full uninstall and reinstall and im not sure if its just me or in TT itself. None of my friends have this issue. If its not a common bug or just on my side please let me know. I get this error: 

![Screenshot 2022-03-19 185904](https://user-images.githubusercontent.com/101999138/159189063-6563f52f-d7b8-441b-9706-7c7eb938c0b6.png)

**Comment by Squall-Leonhart** [comment]
Texturing assistance can be had on the discord.
