### ISSUE TITLE
Unable to select any options under the Character tab when making a modpack

### ISSUE THREAD

**Issue by LiiLiiff14** [TexTools/FFXIV_TexTools_UI#166]
Doesn't matter if I use advanced or standard modpack, I cannot make a modpack of anything located under the "Character" drop down. That includes tails, hair, ears, skin textures, face models and textures. Examples below. I have reinstalled textools twice, did a redownload of indexes, and started over twice now. 
![378f99ad3abd455d3c389d754bb1c95e-png](https://user-images.githubusercontent.com/102050207/159302254-672df756-f8ee-4ea8-a9c6-bbf2c2353a37.jpg)
![65444b6b51be900b8dfec194525057b8-png](https://user-images.githubusercontent.com/102050207/159302256-d1013823-26b4-4199-b8b5-2d1b59a103b4.jpg)

**Comment by Squall-Leonhart** [comment]
This seems to involve either an outdated item set or bad cached data, or both, assistance for it can be had on the discord.

**Comment by fleijaa** [comment]
I'm having this same issue.
It also does not work for item converter or change on install. 
Have also reinstalled TT numerous times and completely refreshed my indexes. Please help.

**Comment by snoebean** [comment]
hi i'm also having the same issue. also reinstalled TT a few times and nothing is working. bump!

**Comment by Squall-Leonhart** [comment]
reinstall the game and textools
update the item sets file.
