### ISSUE TITLE
[Feature Request] Show a prompt during a mass import when one mod would overwrite another

### ISSUE THREAD

**Issue by Kussie** [TexTools/FFXIV_TexTools_UI#17]
When installing multiple ttmps at once, it imports them all one after the other which is great.  Though it might be nice to show a prompt when another mod is already active that the current install would overwrite.

Could be a prompt asking if the user "wants to overwrite the existing active mods?" and have the option of Yes to All, Yes, No or something along those lines

**Comment by Lunaretic** [comment]
The import dialog already displays whether or not you currently have an active mod for each item.
