### ISSUE TITLE
Corrupt Color data file (chara/xls/charamake/human.cmp)

### ISSUE THREAD

**Issue by Yuki-Codes** [TexTools/FFXIV_TexTools_UI#171]
It appears that tex tools is corrupting the chara/xls/charamake/human.cmp file during mod installation somehow. Anamnesis reads this file for skin color information. (https://github.com/imchillin/Anamnesis/issues/986)

A clean indexes fixes the issue, however applying a backup modpack carries the corruption somehow.

**Comment by KoraLyn** [comment]
Any ideas on what the users did that could trigger this issue? TexTools only makes change to `human.cmp` to apply racial scaling settings from what I can tell. I've tried a bunch of different combinations of racial scaling changes, packed them into a backup modpack, started over and installed it, disabled/enabled them but nothing I did resulted in an error when reading the file using Lumina.

**Comment by Yuki-Codes** [comment]
No idea, but its affected several users. We may be able to get a backup modpack from @S1lentSymphony that introduces the bug shared?

**Comment by S1lentSymphony** [comment]
> No idea, but its affected several users. We may be able to get a backup modpack from @S1lentSymphony that introduces the bug shared?

I'll see if I can recover it with the tools I have, but I recently wiped my recycle bin out after deleting my backup modpacks because they were taking up space. I'll see what the results are like in the morning.

**Comment by S1lentSymphony** [comment]
No such luck. Maybe check with one of the others it impacted?

**Comment by MuseMKR** [comment]
I have not done the 'Start Over' option in Anamnesis to correct the 'Corrupt Color Data File'. If someone can instruct me on how to get the files that would show the 'bug', I will get it and post it for diagnosis.

**Comment by S1lentSymphony** [comment]
So if you've created a backup mod pack, the easiest way to find out where
they are (because I don't remember off the top of my head) is just click
import modpack, and look at the folder it opens. Your backup modpack will
be in there.

**Comment by MuseMKR** [comment]
I have created the backup mod pack. Where to I upload it so that it might aid in finding the cause? (It is a 7GB file)

**Comment by KoraLyn** [comment]
Mega or Google Drive will probably work. Though since racial scaling mods are a possible culprit can you check if you actually have any of those, back only those mods up and upload that as well? It should be much much smaller that way so I can take a preliminary look without you having to upload a 7GB file.

**Comment by MuseMKR** [comment]
I do not use any 'racial scaling mods' according to toggling only that option during an XIV Mod Archive search. However, only two mods populated during that search, and I do not use either. Are they any other culprit mod categories? I use gear mods, face mods, minion mods, body replacement mods, hair mods and 1 mount mod.

> Mega or Google Drive will probably work. Though since racial scaling mods are a possible culprit can you check if you actually have any of those, back only those mods up and upload that as well? It should be much much smaller that way so I can take a preliminary look without you having to upload a 7GB file.

**Comment by S1lentSymphony** [comment]
Racial scaling can be applied to all kinds of different mods. It won't
likely be a tag on XMA for anything aside from super specific stuff

**Comment by MuseMKR** [comment]
Would it racial scaling be considered as a mod that changes the scale of any physical part of a character in game (whether character, minion, mount or NPC)? If so, that would be most of I use. I am working on uploading the modpack backup I made earlier. I will post a link here once it completes. It will take about 1.5 hours from now (with no interruptions).

**Comment by KoraLyn** [comment]
Nah, it'd be a mod that modifies the max/min character length, tail length or bust slider scaling. One is for example included with T&F Gen3 though it's optional and I wasn't able to reproduce the error with that modpack on a clean install at least.

**Comment by S1lentSymphony** [comment]
Yeah, a clean install of everything after downloading index backups,
starting over, and reinstalling everything 1 by 1

**Comment by MuseMKR** [comment]
I use a mod that increases the AuRa tail length, for male and female AuRa and a mod that adjusts muscle tone for female characters. I also use a mod that changes Hrothgar body and Highlander/Midlander male body. I will make a modpack that has only the mods that I mentioned in this message. It looks to be less than 900MB. I will post a link after it is done uploading.

**Comment by MuseMKR** [comment]
https://drive.google.com/file/d/1WBBD60CWGeEI7PT7leNMpt2KTgMPbyuE/view?usp=sharing Here is the link to the modpack backup ttmp file I mentioned in my post above. Let me know if it does not work and I will figure out how to make it work. (I'm not too computer savvy as far as One Drive)

**Comment by KoraLyn** [comment]
I wasn't able to reproduce the error using that pack. None of the mods in there are actually racial scaling mods so the file giving the error in Lumina wasn't actually modified. Racial scaling mods are listed under the `Racial Scaling` category in the modlist when filtering by item:

![image](https://user-images.githubusercontent.com/59175928/164890366-9d15dca2-0a49-4cbd-b41a-4b0d6684f9ff.png)

Can you double check if you have any of those in the rest of the backup pack?

**Comment by MuseMKR** [comment]
I have attached two images to this post. The first will be the error I receive upon loading Anamnesis after FFXIV is open and I am in game with my main character. The second will be FFXIV Textools showing the racial scaling category. While the 'parent' category is highlighted, no mods show up in 'Preview List'. Please let me know if I am doing anything wrong, and then direct me on what else needs to be done. :)
![Post FFXIV 6 1 Anamnesis Update Error](https://user-images.githubusercontent.com/103608109/164944300-f1d7b1af-3083-4ae7-9af4-850089c6b89f.png)
![FFXIV Textools Racial Scaling Mod List](https://user-images.githubusercontent.com/103608109/164944312-a22877a5-a3b5-458a-8abd-f0573408f957.png)

**Comment by S1lentSymphony** [comment]
So. Things have changed a bit. It's the same error but in a different place.

Screenshot of the error and quick screenshot of racial scaling attached. Will upload backup modpack and post just in case. Anamnesis functions properly on launch, but when you go to edit gear, you get this error.

Only started with 6.11

https://drive.google.com/file/d/1rWUUNoT6CkI3uy9swRE8attjalpIwuRm/view?usp=sharing

![racial scaling](https://user-images.githubusercontent.com/103521331/165404845-943e3d82-fac3-453f-90d6-2deea9b4fae1.png)
![arith op](https://user-images.githubusercontent.com/103521331/165404849-9c051d6c-a8a5-4edf-94b0-3b228df5540e.png)

**Comment by Squall-Leonhart** [comment]
overflow means a buffer is too small somewhere, its unrelated to the corruption reported.

import this and then run check for problems

https://cdn.discordapp.com/attachments/802338126940340225/968503039814144001/NPC_Defined_d1057_var2_fix.ttmp2

current textools version will abort the check on variant 2 of dark meteion's body otherwise.

**Comment by dekz0rs** [comment]
small group of us having same issue as well, tried the above fixes, installing anything from prior to 6.11 seems to reproduce the issue. Tested with backups and older mods ranging from march this year to mid 2020, not sure what changed in the update honestly. Older backups don't work either, or even selecting parts.

Validated on a clean install of ffxiv that it does work if TT is not present with any mods at all.

Attempted to install the fix above for racial scaling in case + disabled any and all racial settings ( from TF ) but no luck. Any other suggestions on where to possibly look?

**Comment by S1lentSymphony** [comment]
It is in fact related at least somewhat. Because on the original issue
filed with anamnesis, fixing the first one, caused the buffer issue to show
up.

**Comment by Squall-Leonhart** [comment]
Are you using Textools "Redirect imports to lumina" feature?

**Comment by dekz0rs** [comment]
> Are you using Textools "Redirect imports to lumina" feature?

I am not, I don't have any of the additional options checked. Is Lumina required?

**Comment by Squall-Leonhart** [comment]
Kora has a reproduction thanks to @S1lentSymphony 's upload

**Comment by dekz0rs** [comment]
Ah glad to hear, I'll wait to see what they post then, thanks will let the others know.

**Comment by Cleftobismal** [comment]
Hey I'm having the same issue noted here. I would just like to check in if the Fix has been posted for this issue. May I request an update on this at your convenience? =) Thank you kind sir!

**Comment by Squall-Leonhart** [comment]
this bug will be updated when a change has been made.

**Comment by fetchgames** [comment]
> It appears that tex tools is corrupting the chara/xls/charamake/human.cmp file during mod installation somehow. Anamnesis reads this file for skin color information. ([imchillin/Anamnesis#986](https://github.com/imchillin/Anamnesis/issues/986))
> 
> A clean indexes fixes the issue, however applying a backup modpack carries the corruption somehow.

I also have this issue, I have a lot of mods installed please fix this.

**Comment by chirpxiv** [comment]
This was a bug in Lumina that has now been fixed (NotAdam/Lumina#43), that prevented certain files from being read properly.

To summarise:
In a vanilla install, dat files are split into even chunks of around ~2 GB.
TexTools ignores this, resulting in dat files that are extremely bloated in size.
This meant that the offsets for certain files could be raised to a point where they can't be stored as a uint32, which triggered an int overflow caused by a typecast in the wrong place, leading to junk data being read from the game.

**Comment by KoraLyn** [comment]
Ah yea, that makes sense. Thanks for the update. Closing this issue.

**Comment by dekz0rs** [comment]
> Ah yea, that makes sense. Thanks for the update. Closing this issue.

Does that mean a fix is still being rolled out ? I don't use Lumina but still have the same issue, so would this still fix it for me? Or was the person that submitted the file using lumina specifically ?

**Comment by KoraLyn** [comment]
I assume it'll be included in the next release of Lumina which is a library that Anamnesis uses. After that, Anamnesis can be updated with the new Lumina version and then the issue should be solved on your end.
