### ISSUE TITLE
Can't import Gen3 texture with Lumina importing

### ISSUE THREAD

**Issue by catthou** [TexTools/FFXIV_TexTools_UI#176]
````
---------------------------
Error Importing Texture
---------------------------
There was an error Importing the Texture.

Error Message:
Offset plus count is larger than the length of target array.
---------------------------
OK   
---------------------------
````

This is the error message that results from trying to import a Gen3 compatible DDS from [this freckles mod](https://www.xivmodarchive.com/modid/34334) via TexTools while "Redirect imports to Lumina" is checked. No error occurs when importing into DAT.

I followed [this guide](https://docs.google.com/presentation/d/1Zd8590NgaJ4m4N9dYAmv1j0MxWT4kDgkRXoX4AhaYuo/edit#slide=id.g1077ef518f5_0_86) to set up my textools/penumbra environment. Let me know if there's anything else I can provide to help.

**Comment by bryanh-9** [comment]
If you're still having a problem with this, I found a working, if not clunky, work around.

If you turn off lumina mode, you can then import the texture. I recommend installing your body mod temporarily to textools so you can match the appropriate body textures, so it gets the path correct, but that's technically optional, I would think. From there you can export it again, which places it in a folder accessible by clicking the folder icon on the bottom right. You can now disable mods, and re-enable lumina mode, and you should be able to import this "cleaned" texture as you expected.

It's very convoluted, but for whatever reason the few textures files that don't import with lumina enabled do seem to import fine without lumina mode on, and exporting again seems to make it compatible as expected.

**Comment by catthou** [comment]
It's been too long to recall clearly, but I think I ended up doing something like what you described. Though a real solution would be figuring out why it won't import and fixing it in textools.

**Comment by Squall-Leonhart** [comment]
the lumina assembly in use by textools has a bug that can't be rectified as nothing newer supports dotnet 4.x

**Comment by Squall-Leonhart** [comment]
This should be fixed already in the current development branch?
