### ISSUE TITLE
No mods when i try to import them

### ISSUE THREAD

**Issue by Zoukii** [TexTools/FFXIV_TexTools_UI#177]
Hi,  when i try to import the mods, i've got nothing in the file where i should have the mods as the pictures on the tutorial
![image_2022-05-02_222907066](https://user-images.githubusercontent.com/86691695/166322397-add384cd-fca4-46b5-951f-0958def74f0e.png)

**Comment by Squall-Leonhart** [comment]
please use the discord for support.
