### ISSUE TITLE
A question about music extract and import (can not modify package“0c0000” )

### ISSUE THREAD

**Issue by papapachin** [TexTools/FFXIV_TexTools_UI#180]
Hi 
I met a question when I try to replace game bgm with textools.
first, when I extract sth from package"0c0000"(where game bgm placed in),it shows"file does not exist"
then I try to import my modified BGM into "0c0000",I use the path like "music/ffxiv/BGM_Ride_Bike.scd",it show import succeed.
but it is not actually working during the game,the game is still playing its original BGM.
by the way,I also try to use penumbra to import the same BGM modpack,it does working.
Is there any solution? Is it because textools cannot read 0c0000's index correctly or for other reasons?

thanks

**Comment by Lunaretic** [comment]
This was most likely an issue with respect to compressed vs uncompressed files, or an expansion DAT.  Should be resolved now either way.
