### ISSUE TITLE
Missing Files.

### ISSUE THREAD

**Issue by XiaoLeeHwa** [TexTools/FFXIV_TexTools_UI#182]
c0101e0204_glv.mdl		✔	✔	✔	✖
Missing File: chara/equipment/e0204/material/v0002/mt_c0101e0204_glv_b.mtrl
Missing File: chara/equipment/e0204/material/v0003/mt_c0101e0204_glv_b.mtrl
Missing File: chara/equipment/e0204/material/v0004/mt_c0101e0204_glv_b.mtrl
	Some files this mod references are missing or disabled.
	This may cause some variants of this model to be invisible in game.

_I'm sure there's an easy fix to this but I'm still new to this whole modding thing. Any help would be greatly appreciated!_

**Comment by quillon1969** [comment]
Where is the solution to this issue?  How can I fix this issue?
