### ISSUE TITLE
Can't use item converter or change destination items

### ISSUE THREAD

**Issue by wanotori** [TexTools/FFXIV_TexTools_UI#183]
so, i was trying to install a hair piece. some things have the options to change the destination item's base port to another base during the installation process. the particular hair i'm trying to use has that option built into its installation. the first time i installed the hair, the change destination button worked just fine. however, i have had to start over in textools due to my mods breaking. since then, i haven't been able to change the destination item.

instead, what happens is i'll try to click on the drop down arrow options. when i click on what i want, or anything really, i'm being told that it's an invalid selection. same thing for the item converter.

![image](https://user-images.githubusercontent.com/106711303/171516252-5990ebe1-a60b-4fc8-ab52-a35b4f83b322.png)

when i click on choose new item and go into the item selection, it just says "invalid selection." usually, clicking on those categories will open up the actual options, like the hair styles. but it's not been letting me do that anymore. i have reinstalled textools. i also started over again, backed up my index files, downloaded and started over, etc. so i'm not sure what's going on, especially when i had no issue with installing + changing destinations or using the item converter, but now it isn't allowing me to click on anything and says it's invalid.

i'm not sure if this is a textools bug (and i kind of hope it's a common issue people are running into, not just myself) but if it is just me, does anyone know how to fix this? thanks!

**Comment by Squall-Leonhart** [comment]
This is an issue involving the item set file, and cached data and can be assisted with on the discord
