### ISSUE TITLE
Spectacle items pulling incorrect model

### ISSUE THREAD

**Issue by Xelecium** [TexTools/FFXIV_TexTools_UI#189]
The model that is pulled when selecting the "Mythril Spectacles" head gear seems to belong to the "Mythril Magnifiers" item instead.

This seems to apply to most, if not all, of the head gear of the "Spectacles" type.

As a similar example: image for Gold Spectacles item: https://na.finalfantasyxiv.com/lodestone/playguide/db/item/217fb3c4a6f
Model for that item does not match (note extra lenses and difference in frame)

**Comment by Squall-Leonhart** [comment]
This is working as expected,

they share the same model and the game specifically disables part of it on the Spectacles variant.

**Comment by Xelecium** [comment]
I see, and the same is done for other related items, such as monocles (with different parts being hidden?)

When I look through the Variants tab, I see that it mentions "Hidden Parts: d,e,f" (and monocles show "Hidden Parts: a,b,c,d,e"). Is there a way I can apply the hiding of those parts when adding the model to the FMV?

**Comment by Squall-Leonhart** [comment]
not right now, and the owner for FMV component has changes that haven't been introduced yet so nobody else has taken it on.
