### ISSUE TITLE
[Feature Request] Add dye options

### ISSUE THREAD

**Issue by UselessGhost** [TexTools/FFXIV_TexTools_UI#19]
Hey, I'm sorry if this isn't the right place to post this but I was trying to find a way to customize what dyes are applied to an item in the viewer and in the export but couldn't find one.

There seems to be a setting called DyeColors in CustomModelColors in the modding framework but as far as I can tell it's completely unused. I know this is probably not a priority at all but is there any hope of getting this attribute in the CustomModelColors struct implemented?

**Comment by Lunaretic** [comment]
It'll probably get added eventually, but isn't a high priority item at the moment.

**Comment by Lunaretic** [comment]
Closed as will-not-implement.  Users can edit the colorset and such far more easily now and 'custom dyes' are really just colorset edits.
