### ISSUE TITLE
Install Directory Out Of Date

### ISSUE THREAD

**Issue by johan-sorman** [TexTools/FFXIV_TexTools_UI#191]
Unable to select /game/sqpack/ffxiv folder. Using steam version. 
Folderpath is ..\steamapps\common\FINAL FANTASY XIV Online\game\sqpack\ffxiv

Error message:

Install Directory Out Of Date
The install location chosen is out of date

Please locate the following directory.

.../FINAL FANTASY XIV - A Realm Reborn/game/sqpack/ffxiv

**Comment by Squall-Leonhart** [comment]
This is not a bug.
