### ISSUE TITLE
Veena Face Textures arent listed in Modlist

### ISSUE THREAD

**Issue by Rias92** [TexTools/FFXIV_TexTools_UI#198]
Im not able to export a TTMP that changes Veena Iris. Just the 4 Rava faces are exportable.

I originally wanted to create a TTMP that gives Veena makeup and Iris but it wasnt possible to export it. Face 0001(2,3,4) is viable face 0101(2,3,4) isnt

**Comment by Squall-Leonhart** [comment]
duplicate of #134
