### ISSUE TITLE
not enough disk space

### ISSUE THREAD

**Issue by OhLookItsEos** [TexTools/FFXIV_TexTools_UI#200]
I've no idea what is going on but, for some odd reason, I don't have enough disk space, while last week I could just add my mods without a problem and was working fine. and all my drives there is space free so I don't get what I'm doing wrong

![298153791_439111134942693_3827912031525088947_n](https://user-images.githubusercontent.com/111021974/184146941-81433f9e-1116-470f-a0b8-4c644171e3ba.png)

**Comment by Squall-Leonhart** [comment]
Free up space on C: or relocate the user Temp folder.
