### ISSUE TITLE
[Feature Request]Simple Detail List view mode for the installed Mod List

### ISSUE THREAD

**Issue by B01scout** [TexTools/FFXIV_TexTools_UI#203]
I believe I got an idea to improve the Mod List management:
Create a new view mode of the Mod List by creating a Simple Detail List just like it's used with the BASIC MODPACK CREATOR. Keep the same buttons as SELECT ALL, SELECT ACTIVE, CLEAR SELECTED, CANCEL. Keep the search box to filter strings.
Add new buttons like DELETE and DISABLE.
Add new filter like filter by gear type e.g. head, body, hands, legs, feet. And add a column for gear type.

This way versatile users could manage installed mods much faster and in an orderly manner by deleting or disabling many mods with a few clicks. The tree like structure of the current Mod List does not support disabling or deleting e.g. two seperate gear items simultaneously.

**Comment by Lunaretic** [comment]
This should probably be implemented alongside a better, more standardized file list view/user control.  There are too many cases where we want to list the status of a set of file paths that currently either don't exist or use random custom interfaces.

**Comment by Lunaretic** [comment]
The modpack list has gotten a handful of upgrades to address some of these requests.  The rest are likely iceboxed as we move towards TT as a mod authoring tool first and foremost over a mod loader.
