### ISSUE TITLE
After new patch i forget make backup modpacks but i did after so im getting this Error now

### ISSUE THREAD

**Issue by Mikasa342** [TexTools/FFXIV_TexTools_UI#204]
![TEXTOOL ISSUE](https://user-images.githubusercontent.com/110933678/186146253-e6cad605-ef49-4270-be08-ebb064cc4d9a.PNG)

So i created backup modpacks after loading new patch, i got those errors i wonder if i should do anything ?

**Comment by Squall-Leonhart** [comment]
Your backup mod pack is dead due to part of the modded data being overwritten with official data.

**Comment by Mikasa342** [comment]
I'm having invisible mods like body bottom looks invisible and some npcs having no upper body , but its not affecting to my game so much so im thinking I'll starts over everything after again and add all mods as manual one by one again and make a new fresh backup modpacks because i cant see solution , its hard to identify those face and top and bottom mod errors on  error window tab.
