### ISSUE TITLE
TexTools Update 2.3.8.2 Crash when clicking on the emperor's new robe 

### ISSUE THREAD

**Issue by GoddessStar** [TexTools/FFXIV_TexTools_UI#209]
I Keep Getting a crash when i click on category gear body the emperor's new robe i did a backup and start over with no mods and it still will crash with the same error

![Screenshot 2022-08-25 033423](https://user-images.githubusercontent.com/107044049/186561209-1c757b4f-2ba1-4384-a384-f950c050cb80.png)
![Screenshot 2022-08-25 033441](https://user-images.githubusercontent.com/107044049/186561216-25e20652-b41d-40db-8a27-3bb0871750e4.png)
![Screenshot 2022-08-25 033502](https://user-images.githubusercontent.com/107044049/186561222-34f94a01-9706-4de0-8dc6-bac709be9037.png)

**Comment by Squall-Leonhart** [comment]
This is an issue with your game data, join the textools discord for assistance

**Comment by ghost** [comment]
I'm seeing a similar crash since the patch. Going to reinstall everything and see if that works.
