### ISSUE TITLE
Error when importing a bmp or png face texture

### ISSUE THREAD

**Issue by Paupau0730** [TexTools/FFXIV_TexTools_UI#210]
![obraz_2022-08-25_112435164](https://user-images.githubusercontent.com/112075561/186628090-7f7027e3-0cae-4c41-80d9-30b66033aa15.png)
I can't import my custom .png/.bmp face texture. Before 6.2 I could import it without problems.

**Comment by Squall-Leonhart** [comment]
Your PNG is saved in the incorrect pre-multiplied format that photoshop now uses, save it with Safe/Export for Web instead.

**Comment by Paupau0730** [comment]
Got it, thanks for help!
