### ISSUE TITLE
Unable to install mods after 6.2?

### ISSUE THREAD

**Issue by Orgoreyn** [TexTools/FFXIV_TexTools_UI#211]
I keep having this issue after 6.2. I've started over multiple times, and currently have no mods installed. Can someone help me figure out what I'm doing wrong? Thanks.

![Screenshot (80)](https://user-images.githubusercontent.com/78384412/186694376-8039b0be-7623-4219-aa96-750bd9b64ac7.png)

**Comment by Squall-Leonhart** [comment]
Your modpack was made after patching, the data for these items was overwritten.
