### ISSUE TITLE
Uninstalled and started over. Mods crash game.

### ISSUE THREAD

**Issue by Tabukina** [TexTools/FFXIV_TexTools_UI#212]
Hi there, i recently started over, uninstalled and reinstalled tex tools for a fresh restart, but now i get this error with my 5 mods
![TEXTOOLS ERROR](https://user-images.githubusercontent.com/112124371/186757966-b08167d8-7436-455d-85d0-9a0b46bc42b9.PNG)
![TEXTOOLS ERROR2](https://user-images.githubusercontent.com/112124371/186757986-342f7045-ee53-40d5-ae49-9500949238a3.PNG)

I also did a "check for problems" and there were no errors found in the check

**Comment by Squall-Leonhart** [comment]
This is an issue with your game data, join the textools discord for assistance
