### ISSUE TITLE
textools causing extreme gear clipping since 6.2

### ISSUE THREAD

**Issue by astrophonic** [TexTools/FFXIV_TexTools_UI#214]
i had to "start over" in textools due to mods not working anymore, and ever since doing so every piece of gear clips and overlaps on to each other. for example: my character wears thigh high boots that cover his pants, but ever since starting over in textools the pants are now unhidden and clipping with the boots. here's an screenshot of the clipping:

![image](https://user-images.githubusercontent.com/112280781/187046767-812db83e-be99-4321-bd2b-b046cb47bb03.png)

it extends past gear as well. i noticed that even tho my friends character is wearing a hat, his ears appear and also his bangs are unhidden. also his legs are just entirely gone?????

![image](https://user-images.githubusercontent.com/112280781/187046798-708ba7c7-f221-4fc0-8097-d9151a8570bc.png)

i know for a fact that this is a textools issue, as this didn't start happening until i tried to get my mods to appear in textools

**Comment by Squall-Leonhart** [comment]
This is an issue with your game data, join the textools discord for assistance
