### ISSUE TITLE
Maintenance broke Tex tools

### ISSUE THREAD

**Issue by cellus539** [TexTools/FFXIV_TexTools_UI#217]
After todays maintenance patch, I opened tex tools and it had an updated, as expected. After this update, my game would repeatedly crash at relaunch and even when I disabled all the mods, it continued to state unexpected error. I've had to start reinstalling ff, and my partner is unable to get any mod to currently work either, some crashing her out, other flat out not functioning.

**Comment by Squall-Leonhart** [comment]
Textools is fine, no changes were made to moddable data.


Join the textools discord for assistance.
