### ISSUE TITLE
Metadata entries

### ISSUE THREAD

**Issue by TheValkyrie80** [TexTools/FFXIV_TexTools_UI#219]
I have been trying since last night you set my mods back since maintenance and this is what happening. This is the 1st time it has done this after a new patch. Please help.
![Capture](https://user-images.githubusercontent.com/112454800/187428853-6544e3a5-b943-4144-86fd-6c5ccd52d409.PNG)

**Comment by Squall-Leonhart** [comment]
This is an issue with your game data, join the textools discord for assistance
