### ISSUE TITLE
tt update crashs

### ISSUE THREAD

**Issue by bodkonian** [TexTools/FFXIV_TexTools_UI#224]
with the new update on text tools, it now causes the game to crash.
once i disable everything, i can log in.
once i also disable everything, certain body parts are disappearing from my characters, i have the mod off.
only solution is to
remove text tools from pc and never use it so i can play the game and not have things disappear once i have disable everything.
this never was an issue before the update for 6.2

**Comment by Squall-Leonhart** [comment]
This is an issue with your game data, join the textools discord for assistance
