### ISSUE TITLE
Unable to determine EQP set offset for The Emperor's New Boots

### ISSUE THREAD

**Issue by Andyborch1** [TexTools/FFXIV_TexTools_UI#226]
As of version **2.3.8.2** I am getting this error whenever I try to save the Metadata for **The Emperor's New Boots** if I have checked any unchecked **race**. This issue didn't occur prior to the latest patch.
![image](https://user-images.githubusercontent.com/113322719/189569389-c13dbd85-d34a-4716-ae91-2be8061bc5ff.png)

**Comment by Squall-Leonhart** [comment]
This is an issue with your game data, join the textools discord for assistance
