### ISSUE TITLE
HELP!!!!!!!!!ERROR:open Maximum data size limit reached for DAT: 040000,Switched DX9 is uselessQAQ

### ISSUE THREAD

**Issue by MisakiMik** [TexTools/FFXIV_TexTools_UI#229]
There were errors importing some mods.

Name: mt_c1801f0249_fac_a.mtrl
Path: chara/human/c1801/obj/face/f0249/material/mt_c1801f0249_fac_a.mtrl
Import Stage: Data Writing
Error: Maximum data size limit reached for DAT: 040000

Name: mt_c1401f0249_fac_a.mtrl
Path: chara/human/c1401/obj/face/f0249/material/mt_c1401f0249_fac_a.mtrl
Import Stage: Data Writing
Error: Maximum data size limit reached for DAT: 040000

Name: mt_c0801f0249_fac_a.mtrl
Path: chara/human/c0801/obj/face/f0249/material/mt_c0801f0249_fac_a.mtrl
Import Stage: Data Writing
Error: Maximum data size limit reached for DAT: 040000

Name: mt_c0601f0249_fac_a.mtrl
Path: chara/human/c0601/obj/face/f0249/material/mt_c0601f0249_fac_a.mtrl
Import Stage: Data Writing
Error: Maximum data size limit reached for DAT: 040000

Name: mt_c0201f0250_fac_a.mtrl
Path: chara/human/c0201/obj/face/f0250/material/mt_c0201f0250_fac_a.mtrl
Import Stage: Data Writing
Error: Maximum data size limit reached for DAT: 040000

Name: mt_c1401t0104_a.mtrl
Path: chara/human/c1401/obj/tail/t0104/material/v0001/mt_c1401t0104_a.mtrl
Import Stage: Data Writing
Error: Maximum data size limit reached for DAT: 040000

Name: mt_c1401t0103_a.mtrl

**Comment by MisakiMik** [comment]
CHN version

**Comment by EpicallyFail** [comment]
Confirm I have this as well on ENG, installed a few mod packs and they worked fine, then after a while it failed with the same error.

Should note I'm modding on a Steam Deck, so it could be linux and/or wine.

Existing mods do still work, but I can't seem to add any more.

**Comment by Squall-Leonhart** [comment]
Textools pulls DX renderer from the default launcher's my document path,

you cannot change between dx9 and dx11 without starting over.

Steam deck (linux) is not supported.

**Comment by hoyutofu** [comment]
I figured out what Squall was trying to say, in case it's not obvious to others. You need to go into TexTools and go to Help > "Start Over." Then try your mods again.
