### ISSUE TITLE
BUG report：Textools 2.3.4.17 Fatal errors 

### ISSUE THREAD

**Issue by Sevenrose1978** [TexTools/FFXIV_TexTools_UI#23]
The start over function of FFXIV Textools 2.3.4.17 will cause serious errors after the release of 5.31 patch on Chinese servers on January 5！Executing the start over function of version 2.3.4.17 will cause the file 040000.win32.dat0 to be wrongly overridden, resulting in model loss and other problems

Fix this bug plz，thanks.

**Comment by Squall-Leonhart** [comment]
fixed by 2.3.4.18
