### ISSUE TITLE
The New Fat Cat apparel Top not listed.

### ISSUE THREAD

**Issue by captice** [TexTools/FFXIV_TexTools_UI#230]
New set of items were added in 6.21 called the Fat Cat Attire.
Only the Fat Cat Hood, Slippers and Halfslops are identified by name however the Fat Cat Loungeware is listed as e6154_top_v0.
The other item in the set is a empty hand space called e6154_glv_0 which is nothing at all and not a bug.

I had rebuilt cache twice and searched for new item sets twice also but only the loungeware item remains without a proper name.

**Comment by Squall-Leonhart** [comment]
Already fixed for a future release.

https://github.com/TexTools/FFXIV_TexTools_UI/pull/213
https://github.com/TexTools/xivModdingFramework/pull/48

https://cdn.discordapp.com/attachments/802338126940340225/1013446176298782751/FFXIV_TexTools_Preview.zip

**Comment by Squall-Leonhart** [comment]
Fixed in 2.3.8.2
