### ISSUE TITLE
Some sort of brug (Crash Report 2.3.8.2)

### ISSUE THREAD

**Issue by TheValkyrie80** [TexTools/FFXIV_TexTools_UI#231]
Not sure what is going on.
![TextTools Error](https://user-images.githubusercontent.com/112454800/190839193-22fc9391-b43c-415e-a194-7be5b27f22dc.PNG)

**Comment by Squall-Leonhart** [comment]
This is caused by a missing assembly from the Libs folder, unpacking or reinstalling textools should resolve this.
