### ISSUE TITLE
Multiple errors and crash when adding a certain simple modpack to an advanced one

### ISSUE THREAD

**Issue by Ardgevald** [TexTools/FFXIV_TexTools_UI#232]
# Textools version
2.3.8.2

# Steps to reproduce
- Create new Advanced modpack
- Input info and go to new page
- Add an Option list
- Add a group option
- Load a basic modpack (consistently crashes with the provided one)
- Add it to the option and it crashes

# Current behaviour
It shows three errors back to back before closing

# Error logs
[CrashErrors.txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/9591521/CrashErrors.txt)

# File used for the crash
In [this mod](https://www.xivmodarchive.com/modid/33467), the file called `Afflatus MiseryV2[S]=苦难之心.ttmp2` consistently crashes Textools in the above situation

**Comment by Squall-Leonhart** [comment]
same game data issue as everyone else recently reporting, go to the discord.
