### ISSUE TITLE
error: "there were errors importing some mods, one or more errors occured"

### ISSUE THREAD

**Issue by daydreams12345** [TexTools/FFXIV_TexTools_UI#240]
so i stopped using ffxiv for a while and i just uninstalled my old textools with its mods and reinstalled it. one of the mods i was using, the zenos head replacement, was listed as too far away to reach or disable on that old textools.
reinstalling textools was fine, but when i tried to import the zenos mod again it says that there were errors importing the mods and no other information. 
 the mod in question https://www.xivmodarchive.com/modid/16518

i deleted the old file of the previous head mod too, and starting over textools doesnt change it.

**Comment by daydreams12345** [comment]
update: when trying to use xivlauncher, a warning popped up that said that there was an error opening the game and it could be caused by a faulty textools. i deleted all zenos mod files and uninstalled textools .. but dalamud still pops this up after.
![Screenshot 2022-11-06 125310](https://user-images.githubusercontent.com/117592553/200186848-b075c423-57b6-4527-8baa-620c1b577b03.png)

**Comment by Squall-Leonhart** [comment]
Application support is provided on the discord.
