### ISSUE TITLE
Updated windows 10 Now Texttools won't run

### ISSUE THREAD

**Issue by Raestorms** [TexTools/FFXIV_TexTools_UI#242]
Hi everyone,
I updated my windows 10 to the latest version and now when I try to run textools it says : 
"The feature you are trying to run is on a network resource that is unavailable. Click OK to try again or enter an alternate path to a folder containing the installation package 'Textools_setup.msi"

I tried uninstalling it then reinstalling but then windows acts like its not an .exe file and asks me what program should it try to run it with? The windows update version is 22H2 for x64

Does anyone know how to fix this?

**Comment by Raestorms** [comment]
I got Textools to open again, I redownloaded the zip and unblocked the access in properties as well as set it to run as administrator. However, If I download a new file from the mod archive, I still get the same messages in the above entry. Even if I allow access and run as admin. I try to manually import from textools itself and It seems to enable it, but when I log in, nothing has changed.

**Comment by Squall-Leonhart** [comment]
configure the browsers mimetype handlers to use the new install of textools
