### ISSUE TITLE
[Feature Request] Import unpacked mod

### ISSUE THREAD

**Issue by priprii** [TexTools/FFXIV_TexTools_UI#245]
Currently it's only possible (unless I'm missing something) to import a ModPack if it's packed as a ttmp2 file.

If you install a ttmp2 mod in Penumbra and want to free up storage by deleting the ttmp2 file, you won't be able to edit the mod in future.

So I'm proposing the addition of an import option for importing a mod that has been unpacked, or the ability to repack an unpacked mod back into a ttmp2 file.

**Comment by Squall-Leonhart** [comment]
raw files can be replaced one by one

**Comment by priprii** [comment]
The raw file import never seems to work for me. They import successfully, but the model viewer has issues with them.

When importing models:

> There was an error reading the MDL file.
> Unable to read beyond the end of the stream.

or

> Non-negative number required.
> Parameter name: count

And textures:

> Unable to load texture file:
> Error:There was an error reading texture data at offset XXXXX

These errors prevent exporting as well as viewing and they occur for everything I try to import through the raw method, even unchanged textures. Am I doing something wrong?

**Comment by Lunaretic** [comment]
Resolved with import/export of .PMP, Penumbra folders, and raw uncompressed files in Dawntrail builds.
