### ISSUE TITLE
"Apply Deformation Shapes" ignored in FMV and export

### ISSUE THREAD

**Issue by yungslime** [TexTools/FFXIV_TexTools_UI#25]
Hi! I'm unsure if this is intended behavior or not but I've noticed that, when applying deformation shapes on a model (Hrothgar face in this case), the changes are completely ignored when opening the model in the FMV or when exporting it. 

Am I missing something or is this functionality not supported? I joined the discord server but could not find anyone asking the same question.

I am using TexTools v2.3.4.19.

Thanks!

**Comment by yungslime** [comment]
Nvm, sorry, just learned about shapekeys. 🤦

**Comment by Goowilome** [comment]
Hey, I know this was closed but I'm new and experiencing that same problem. Can you impart your secret knowledge of said Shapekeys?

**Comment by peacchi** [comment]
i am also experiencing this and can't find any help online, if anyone could help me out i would really really appreciate any guidance lol

**Comment by yungslime** [comment]
Hi, yeah! (and i'm sorry @Goowilome, i completely missed this comment)

Exported models contain all the deformation shapes found in the editor, they're mapped to shape keys https://docs.blender.org/manual/en/latest/animation/shape_keys/introduction.html

So you don't actually have to apply them in textools but in blender
