### ISSUE TITLE
[Bug]: Majestic Dress issue

### ISSUE THREAD

**Issue by MorbidA** [TexTools/FFXIV_TexTools_UI#250]
### Expected behavior?

N/A

### Actual behavior?

Adding any mods that interact with the item e9149_top (Majestic Dress) for instance item convert to or from another item while working initially, will cause an The given key was not present in the dictionary error going forward while the mod is installed. Cannot delete or disable the mod either causes the same error. Only starting over removing every mod will make things work again.

Additionally, if you load up the body piece in the model viewer TexTools crashes.

### Steps to reproduce the problem

1. click Item convert
2. select whatever body item
3. select 9149 (Majestic Dress)
4. Create the mod
5. Every action from this point on that interacts with installed mods will cause an given key was not present in the dictionary error. For instance doing item convert on an entirely different item or similar.

### Error messages?

The given key was not present in the dictionary.
![Screenshot 2022-12-16 035049](https://user-images.githubusercontent.com/15589595/208011169-b341adb5-20d2-4783-a471-5d936fafddf1.jpg)

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Item Converter, Importer, Modpack Creator)
Item: (Gear)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
Seems to be an issue with the mod that you're trying to convert, not textools.

**Comment by Squall-Leonhart** [comment]
Oh, i see whats happening, Material ends up out of range after the conversion concludes

**Comment by Squall-Leonhart** [comment]
Issue is unique to this Item and occurs because the Metadata ends up out of bounds after changing the extra skeleton setting for Fem Viera.

**Comment by Lunaretic** [comment]
Fixed in latest version/Dawntrail builds.

As mentioned above, issue was specific to this item as it was the /only/ item with a Viera F Body extra skeleton, and altering it caused TT to (correctly?) believe Viera had no Extra Skeletons.   Fixed now by resolving available extra skeletons against both original and modded files.
