### ISSUE TITLE
[Bug]: 1801h0115 Viera hair missing

### ISSUE THREAD

**Issue by majorpraline** [TexTools/FFXIV_TexTools_UI#252]
### Expected behavior?

Show hair 1801h0115 (FViera hair 115) in the item list.

### Actual behavior?

[https://i.imgur.com/ceMrHsS.png](Advance modpacking 1801h0115)

Trying to pack hair 115 for FViera, it's not appearing in the item list while doing advanced modpacks.

### Steps to reproduce the problem

1. Create advanced modpack
2. Search for FViera hair 115
3.
4.
5.
...

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: Advanced modpack
Item: FViera hair 115 (1801h0115)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
this is the same as #236

**Comment by Lunaretic** [comment]
Unsure if this was an item sets file issue or something else but it's fixed.
