### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by EvelynH03** [TexTools/FFXIV_TexTools_UI#253]
### Expected behavior?

The racial setting should open a screen for editing figures of body ratio.

### Actual behavior?

![Texttool error](https://user-images.githubusercontent.com/122711748/212522270-c0628752-f317-4a80-ad30-3bf1c8738411.PNG)

### Steps to reproduce the problem

1. Open textool
2. Open Tools
3. Edit Racial Setting
4. Click one of the race and gender
5. Error pop
...

### Error messages?

![Texttool error](https://user-images.githubusercontent.com/122711748/212522191-2c533679-f802-478b-88bb-2fbf1d75a276.PNG)

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Just open the tool as normal, the updates were auto run. Then, i apply modpack as usual, went to racial setting and error pop.

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
This is an issue with your Game Data, the editor opens just fine.

**Comment by EvelynH03** [comment]
ok thanks.
