### ISSUE TITLE
[Bug]: Advanced Modpack bug

### ISSUE THREAD

**Issue by midknightmelodee** [TexTools/FFXIV_TexTools_UI#256]
### Expected behavior?

Usually I do create modpack
Advanced Modpack
Load From

Proceeds to add to and edit modpack.

### Actual behavior?

However when I load the modpack it crashes TT and shows the error messages. I was editing this modpack yesterday and had zero issues. I took a small break and when I came back it stopped working and proceeded to crash every time.

### Steps to reproduce the problem

1. Create Modpack
2. Advanced Modpack
3. Load From
4. <Insert Name>
5. Error Messages
...

### Error messages?

![image](https://user-images.githubusercontent.com/123326199/213934962-abd42a73-a65d-41d4-b97c-54dc8d2ee779.png)
![image](https://user-images.githubusercontent.com/123326199/213935020-f4930bfe-3934-41d3-85ef-40a6f00fad97.png)
![image](https://user-images.githubusercontent.com/123326199/213935063-06f78690-f716-44f0-a7e9-f511d5a08cd1.png)
![image](https://user-images.githubusercontent.com/123326199/213935105-041af6d6-94db-4e11-a4f5-dc23f65d900e.png)

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Advanced Modpack loading - trying to build the Advanced modpack and add more options to it. Failed to load the modpack.

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
This isn't demonstrating a bug so much, more that a fault has been introduced in the modpack.

unfortunately it'll be your job to narrow it down to the content of the TTMPD that has the illegal character.

**Comment by Ifalna-Shayoko** [comment]
> This isn't demonstrating a bug so much, more that a fault has been introduced in the modpack.
> 
> unfortunately it'll be your job to narrow it down to the content of the TTMPD that has the illegal character.

I have the same issue since a few weeks. Whenever I try to add an .sklb file to an advanced archive, Textools throws the above errors.

The kicker: The mod works just fine when created as a "Basic modpack" and the skeleton behaves as expected ingame during Amnamnesis posing. It's really just the advanced modpack that goes "ka-boom". Oo

Perhaps this helps you in tracking down the issue.
