### ISSUE TITLE
[Feature] Music index swap

### ISSUE THREAD

**Issue by ArutanSipdrae** [TexTools/FFXIV_TexTools_UI#26]
This was a feature from XIV explorer, which allow to reference the index of another music of the game for the music of our choosing, which allow thing like changing trial mount music for any phase of said trial, or anything we want.
But now it's been discontinued and I think that would be a really nice feature to have on textools since it's all about moding the game.

**Comment by Lunaretic** [comment]
This is theoretically possible via the raw file operations menus, though I have no idea what format the music files are in.  (Additionally, if they're in the expansion DATs, we need to add support for those)

**Comment by ArutanSipdrae** [comment]
They do are in the expansion DATs as well.
The indexes for the musics are in 0c0{expansionNumber}00.win32.index and the musics are in .scd format
expansionNumber = 0|1|2|3

**Comment by Lunaretic** [comment]
Expansion DAT support is something of a longer term issue that needs addressing (but unfortunately is not super trivial to implement due to the way TexTools is structured.)

**Comment by Lunaretic** [comment]
I'm happy to say this ancient issue is finally resolved.  Starting with the Dawntrail builds Textools will be able to read/write to the expansion DATs properly.
