### ISSUE TITLE
[Bug]:  I cannot use TextTools in Windows 7

### ISSUE THREAD

**Issue by Mixiaoqing** [TexTools/FFXIV_TexTools_UI#264]
### Expected behavior?

I hope to receive help or solutions from developers. I am very grateful. I didn't upgrade Windows 10 and Windows 11 because I personally don't like it

### Actual behavior?

![QQ截图20230413233610](https://user-images.githubusercontent.com/130686115/231819291-e2ec2d4e-3474-41c6-9f49-23e14a64b46b.png)

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
https://github.com/TexTools/FFXIV_TexTools_UI/blob/master/readme.md
