### ISSUE TITLE
[Feature request]: Import player appearance data into Textools

### ISSUE THREAD

**Issue by Syogren** [TexTools/FFXIV_TexTools_UI#266]
### Request box

A way to import player appearance data directly into Textools.  The user would import a player appearance data file into the program, and it would automatically select the correct models, morphs, and hair/skin/eye colors, giving the user the corresponding model.  Perhaps also, since Textools already has access to the filepath of the game anyway, the user would be able to simply select any of the appearance datas saved to their machine as well.

Related, but the reverse would also be good, i.e. being able to save the character in the Full Model Viewer as an appearance data file.

### Reason box

Textools already provides the user the ability to manually select parts corresponding to their Warrior of Light, or an NPC, via the Full Model Viewer and its associated components.  However, while this is doable, and easy to do after enough practice, it would be a lot faster to just pass in an appearance data file and have the program do it on its own.

### Examples

Example 1: The user has an appearance data for John Finalfantasy on their computer, and loads the file into Textools.  Textools then automatically populates the Full Model Viewer with the body parts and clothes (if that is stored in the appearance data, otherwise skip that step), resulting in the Full Model Viewer containing all the parts the user would have otherwise had to add manually.

Example 2: The user already has player appearance data in their user Final Fantasy folder.  Textools automatically detects this data, and allows the player to select it from there, skipping the step of manually finding the appearance data elsewhere.  Textools then proceeds as in example 1.

**Comment by Lunaretic** [comment]
This is *theoretically* possible, but would take a significant amount of time to set up.  If someone feels greatly invested to tackle the idea on their own and submit a PR they're welcome to, but otherwise this is a will-not-fix.
