### ISSUE TITLE
[Bug] An error occured when attempting to expand the metadata entries.  Error:Block length does not match with its complement. 

### ISSUE THREAD

**Issue by Horo2** [TexTools/FFXIV_TexTools_UI#267]
### Expected behavior?

This error occurs when I import MODs

### Actual behavior?

![image](https://github.com/TexTools/FFXIV_TexTools_UI/assets/49852694/78449cd8-387d-414d-935f-2c09835b4ad0)

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### Error messages?

An error occured when attempting to expand the metadata entries.  
Error:Block length does not match with its complement. 

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
Indexes or game data is inconsistent with what is expected, use quicklauncher to run a repair, the main launcher will nuke data first.
