### ISSUE TITLE
Error in rebuild

### ISSUE THREAD

**Issue by moahrs** [TexTools/FFXIV_TexTools_UI#27]
Hello... I am with the latest version of the FFXIV, and the latest version of textools, 2.3.4.19, but show the error below, in the start at rebuilding...

An error occurred while attempting to rebuild the cache. This may be caused by this version of Final Fantasy XIV not being supported by this version of TexTools.

Non-negative number required.
Parameter name: count

Need a new version of textools, or what can I do to solve this fix ? thank you...

**Comment by Squall-Leonhart** [comment]
run the launcher and update the game.

**Comment by moahrs** [comment]
> run the launcher and update the game.

I do not understand. My game, FFXIV, is always up to date. This problems starts after the last update of the FFXIV. I think have any problem in the last version before rebuild...  screen savers below.

![image of the process before the error](https://user-images.githubusercontent.com/8331186/107861028-d61af880-6e21-11eb-997e-da55e6df9b1d.png)
![image of the error after the rebuild process](https://user-images.githubusercontent.com/8331186/107861027-d4e9cb80-6e21-11eb-99b0-e9603f152883.png)

**Comment by Squall-Leonhart** [comment]
select the correct client install folder, you have 2 of them - one of them is not up to date.

**Comment by moahrs** [comment]
> select the correct client install folder, you have 2 of them - one of them is not up to date.

Thanks for help. I have only 1 client install folder:

E:\Steam\steamapps\common\FINAL FANTASY XIV Online\game\sqpack\ffxiv

below, the customize screen:

![setup screen](https://user-images.githubusercontent.com/8331186/107864081-dd4d0100-6e37-11eb-8113-ce1dd72188ec.png)

And below, the check problem response:

`Initializing Problem Check....

Checking Index Dat Values....
	0a0000 Index Files	✔		✔
	010000 Index Files	✔		✔
	040000 Index Files	✔		✔
	060000 Index Files	✔		✔

Checking Index Backups....
	0a0000 Index Files	✖
No Backup Found.
	010000 Index Files	✖
No Backup Found.
	040000 Index Files	✖
No Backup Found.
	060000 Index Files	✖
No Backup Found.

Checking For Empty Dat Files....
	0a0000 Dat Files	✔
	010000 Dat Files	✔
	040000 Dat Files	✔
	060000 Dat Files	✔

Checking Modlist....
	mt_c0201e6045_glv_b.mtrl	✔	✔	✔	✔
	mt_c0201e0279_dwn_a.mtrl	✔	✔	✔	✔
	c0201e0000_dwn.mdl		✔	✔	✔	✔
	v01_c0201e9903_dwn_m.tex	✔	✔	✔	✔
	v01_c0201e9903_dwn_n.tex	✔	✔	✔	✔
	mt_c0201e9903_dwn_a.mtrl	✔	✔	✔	✔
	c0201e9903_dwn.mdl		✔	✔	✔	✔
	v01_c0201e0000_dwn_m.tex	✔	✔	✔	✔
	mt_c0201e0000_dwn_a.mtrl	✔	✔	✔	✔
	v01_c0201e0000_dwn_n.tex	✔	✔	✔	✔
	c0201e6045_glv.mdl		✔	✔	✔	✔
	v01_c0201e0279_top_m.tex	✔	✔	✔	✔
	mt_c0201e0279_top_a.mtrl	✔	✔	✔	✔
	c0201e0000_top.mdl		✔	✔	✔	✔
	mt_c0201e9903_top_a.mtrl	✔	✔	✔	✔
	v01_c0201e9903_top_m.tex	✔	✔	✔	✔
	v01_c0201e9903_top_n.tex	✔	✔	✔	✔
	c0201e9903_top.mdl		✔	✔	✔	✔
	mt_c0201e0000_top_a.mtrl	✔	✔	✔	✔
	v01_c0201e0000_top_m.tex	✔	✔	✔	✔
	v01_c0201e0000_top_n.tex	✔	✔	✔	✔
	mt_c0201e0205_glv_b.mtrl	✔	✔	✔	✔
	v01_c0201e0279_sho_n.tex	✔	✔	✔	✔
	v01_c0201e0279_sho_d.tex	✔	✔	✔	✔
	mt_c0201e0279_sho_a.mtrl	✔	✔	✔	✔
	v01_c0201e0279_sho_s.tex	✔	✔	✔	✔
	c0201e0279_sho.mdl		✔	✔	✔	✔
	c0201e9901_sho.mdl		✔	✔	✔	✔
	mt_c0201e9903_sho_a.mtrl	✔	✔	✔	✔
	v01_c0201e9903_sho_s.tex	✔	✔	✔	✔
	v01_c0201e9903_sho_n.tex	✔	✔	✔	✔
	v01_c0201e9903_sho_d.tex	✔	✔	✔	✔
	c0201e9903_sho.mdl		✔	✔	✔	✔
	v01_c0201e0000_sho_d.tex	✔	✔	✔	✔
	mt_c0201e0000_sho_a.mtrl	✔	✔	✔	✔
	v01_c0201e0000_sho_n.tex	✔	✔	✔	✔
	v01_c0201e0000_sho_s.tex	✔	✔	✔	✔
	c0201e0000_sho.mdl		✔	✔	✔	✔
	c0201e0279_glv.mdl		✔	✔	✔	✔
	c0201e9903_glv.mdl		✔	✔	✔	✔
	c0201e0000_glv.mdl		✔	✔	✔	✔
	--c1801b0001_d.tex		✔	✔	✔	✔
	skin_m.tex			✔	✔	✔	✔
	--c1401b0001_s.tex		✔	✔	✔	✔
	--c1801b0001_n.tex		✔	✔	✔	✔
	--c0401b0001_d.tex		✔	✔	✔	✔
	--c0201b0001_n.tex		✔	✔	✔	✔
	--c1401b0001_n.tex		✔	✔	✔	✔
	--c1401b0101_d.tex		✔	✔	✔	✔
	--c0201b0001_d.tex		✔	✔	✔	✔
	--c1401b0001_d.tex		✔	✔	✔	✔
	--c0401b0001_n.tex		✔	✔	✔	✔
	c0201b0005_top.mdl		✔	✔	✔	✔
	c0201b0002_top.mdl		✔	✔	✔	✔
	v01_c0201e0279_dwn_n.tex	✔	✔	✔	✔
	v01_c0201e0279_dwn_m.tex	✔	✔	✔	✔
	c0201e0279_dwn.mdl		✔	✔	✔	✔
	v01_c0201e6045_glv_b_s.tex	✔	✔	✔	✔
	v01_c0201e6045_glv_b_n.tex	✔	✔	✔	✔
	v01_c0201e6045_glv_b_d.tex	✔	✔	✔	✔
	v01_c0201e6080_sho_b_d.tex	✔	✔	✔	✔
	v01_c0201e6080_sho_b_s.tex	✔	✔	✔	✔
	mt_c0201e6080_sho_b.mtrl	✔	✔	✔	✔
	v01_c0201e6080_sho_b_n.tex	✔	✔	✔	✔
	c0201e6080_sho.mdl		✔	✔	✔	✔
	v01_c0201e6045_dwn_c_s.tex	✔	✔	✔	✔
	mt_c0201e6045_dwn_b.mtrl	✔	✔	✔	✔
	v01_c0201e6045_dwn_c_d.tex	✔	✔	✔	✔
	mt_c0201e6045_dwn_c.mtrl	✔	✔	✔	✔
	v01_c0201e6045_dwn_c_n.tex	✔	✔	✔	✔
	v01_c0201e6045_dwn_b_n.tex	✔	✔	✔	✔
	v01_c0201e6045_dwn_b_s.tex	✔	✔	✔	✔
	v01_c0201e6045_dwn_b_d.tex	✔	✔	✔	✔
	c0201e6045_dwn.mdl		✔	✔	✔	✔
	mt_c0201e6045_top_d.mtrl	✔	✔	✔	✔
	v01_c0201e6045_top_d_s.tex	✔	✔	✔	✔
	v01_c0201e6045_top_d_n.tex	✔	✔	✔	✔
	v01_c0201e6045_top_c_n.tex	✔	✔	✔	✔
	v01_c0201e6045_top_b_s.tex	✔	✔	✔	✔
	v01_c0201e6045_top_c_s.tex	✔	✔	✔	✔
	v01_c0201e6045_top_c_d.tex	✔	✔	✔	✔
	v01_c0201e6045_top_b_n.tex	✔	✔	✔	✔
	mt_c0201e6045_top_c.mtrl	✔	✔	✔	✔
	v01_c0201e6045_top_d_d.tex	✔	✔	✔	✔
	v01_c0201e6045_top_b_d.tex	✔	✔	✔	✔
	mt_c0201e6045_top_b.mtrl	✔	✔	✔	✔
	c0201e6045_top.mdl		✔	✔	✔	✔
	v01_c0201e0279_top_n.tex	✔	✔	✔	✔
	c0201e0279_top.mdl		✔	✔	✔	✔
	v01_c0201e0205_dwn_b_s.tex	✔	✔	✔	✔
	v01_c0201e0205_glv_b_d.tex	✔	✔	✔	✔
	mt_c0201e0205_dwn_b.mtrl	✔	✔	✔	✔
	mt_c0201e0205_top_d.mtrl	✔	✔	✔	✔
	c0201e0205_sho.mdl		✔	✔	✔	✔
	v01_c0201e0205_sho_c_s.tex	✔	✔	✔	✔
	v01_c0201e0205_sho_c_n.tex	✔	✔	✔	✔
	v01_c0201e0205_sho_c_d.tex	✔	✔	✔	✔
	mt_c0201e0205_sho_c.mtrl	✔	✔	✔	✔
	mt_c0201e0205_top_c.mtrl	✔	✔	✔	✔
	v01_c0201e0205_sho_b_n.tex	✔	✔	✔	✔
	v01_c0201e0205_sho_b_d.tex	✔	✔	✔	✔
	mt_c0201e0205_sho_b.mtrl	✔	✔	✔	✔
	v01_c0201e0205_dwn_d_s.tex	✔	✔	✔	✔
	v01_c0201e0205_dwn_d_n.tex	✔	✔	✔	✔
	v01_c0201e0205_dwn_c_s.tex	✔	✔	✔	✔
	v01_c0201e0205_dwn_b_d.tex	✔	✔	✔	✔
	v01_c0201e0205_dwn_d_d.tex	✔	✔	✔	✔
	v01_c0201e0205_dwn_b_n.tex	✔	✔	✔	✔
	v01_c0201e0205_dwn_b_m.tex	✔	✔	✔	✔
	mt_c0201e0205_dwn_d.mtrl	✔	✔	✔	✔
	mt_c0101e0305_top_a.mtrl	✔	✔	✔	✔
	mt_c0101e0305_top_a.mtrl	✔	✔	✔	✔
	mt_c0201e0205_dwn_c.mtrl	✔	✔	✔	✔
	mt_c0101e0305_top_a.mtrl	✔	✔	✔	✔
	mt_c0101e0305_top_a.mtrl	✔	✔	✔	✔
	c0201e0205_dwn.mdl		✔	✔	✔	✔
	c0201e0205_top.mdl		✔	✔	✔	✔
	v01_c0201e0205_sho_b_m.tex	✔	✔	✔	✔
	c0101e0305_top.mdl		✔	✔	✔	✔
	mt_c0101e5043_met_a.mtrl	✔	✔	✔	✔
	mt_c0101e6067_sho_a.mtrl	✔	✔	✔	✔
	mt_c0101e6013_sho_b.mtrl	✔	✔	✔	✔
	v01_c0101e5043_met_d.tex	✔	✔	✔	✔
	v01_c0201e0205_glv_b_s.tex	✔	✔	✔	✔
	v01_c0201e0205_glv_b_n.tex	✔	✔	✔	✔
	c0201e0205_glv.mdl		✔	✔	✔	✔
	v01_c0201e0205_sho_b_s.tex	✔	✔	✔	✔
	v01_c0201e0205_dwn_c_n.tex	✔	✔	✔	✔
	v01_c0201e0205_dwn_c_d.tex	✔	✔	✔	✔
	v01_c0201e0205_top_c_n.tex	✔	✔	✔	✔
	v01_c0201e0205_top_d_n.tex	✔	✔	✔	✔
	v01_c0201e0205_top_c_d.tex	✔	✔	✔	✔
	v01_c0201e0205_top_d_s.tex	✔	✔	✔	✔
	v01_c0201e0205_top_e_d.tex	✔	✔	✔	✔
	v01_c0201e0205_top_c_s.tex	✔	✔	✔	✔
	v01_c0201e0205_top_d_d.tex	✔	✔	✔	✔
	v01_c0201e0205_top_b_d.tex	✔	✔	✔	✔
	v01_c0201e0205_top_b_s.tex	✔	✔	✔	✔
	v01_c0201e0205_top_b_n.tex	✔	✔	✔	✔
	mt_c0201e0205_top_b.mtrl	✔	✔	✔	✔
	v01_c0101e0305_top_n.tex	✔	✔	✔	✔
	v01_c0101e0305_top_m.tex	✔	✔	✔	✔
	c0201e0305_top.mdl		✔	✔	✔	✔
	v03_c0101e0305_top_n.tex	✔	✔	✔	✔
	c0901e0305_top.mdl		✔	✔	✔	✔
	c0301e0305_top.mdl		✔	✔	✔	✔
	c1101e0305_top.mdl		✔	✔	✔	✔
	v01_c0101e5043_met_s.tex	✔	✔	✔	✔
	c1801e5043_met.mdl		✔	✔	✔	✔
	v01_c0101e5043_met_n.tex	✔	✔	✔	✔
	c0201e5043_met.mdl		✔	✔	✔	✔
	v01_c0101e6067_glv_m.tex	✔	✔	✔	✔
	c0201e6067_glv.mdl		✔	✔	✔	✔
	v01_c0101e6067_glv_n.tex	✔	✔	✔	✔
	049590.tex			✔	✔	✔	✔
	mt_c0101e6067_glv_a.mtrl	✔	✔	✔	✔
	v01_c0201e6068_top_n.tex	✔	✔	✔	✔
	mt_c0201e6068_top_a.mtrl	✔	✔	✔	✔
	v01_c0201e6068_top_m.tex	✔	✔	✔	✔
	c0201e6068_top.mdl		✔	✔	✔	✔
	043407.tex			✔	✔	✔	✔
	v01_c0101e6067_sho_n.tex	✔	✔	✔	✔
	v01_c0101e6067_sho_m.tex	✔	✔	✔	✔
	c0201e6067_sho.mdl		✔	✔	✔	✔
	047145.tex			✔	✔	✔	✔
	c0201e6068_dwn.mdl		✔	✔	✔	✔
	049814.tex			✔	✔	✔	✔
	v01_c0201e6068_dwn_n.tex	✔	✔	✔	✔
	v01_c0201e6068_dwn_m.tex	✔	✔	✔	✔
	mt_c0201e6068_dwn_a.mtrl	✔	✔	✔	✔
	c0201e0050_top.mdl		✔	✔	✔	✔
	mt_c0201e0619_top_c.mtrl	✔	✔	✔	✔
	v01_c0101e0619_top_c_m.tex	✔	✔	✔	✔
	v01_c0101e0619_top_c_n.tex	✔	✔	✔	✔
	mt_c0201e0619_top_c.mtrl	✔	✔	✔	✔
	c0201e0619_top.mdl		✔	✔	✔	✖
Missing File: chara/equipment/e0619/material/v0003/mt_c0201e0619_top_b.mtrl
Missing File: chara/equipment/e0619/material/v0003/mt_c0201e0619_top_c.mtrl
Missing File: chara/equipment/e0619/material/v0004/mt_c0201e0619_top_b.mtrl
Missing File: chara/equipment/e0619/material/v0004/mt_c0201e0619_top_c.mtrl
	Some files this mod references are missing or disabled.
	This may cause some variants of this model to be invisible in game.
	mt_c0101e0618_dwn_b.mtrl	✔	✔	✔	✔
	mt_c0101e0618_dwn_b.mtrl	✔	✔	✔	✔
	mt_c0101e0618_dwn_b.mtrl	✔	✔	✔	✔
	mt_c0101e0618_dwn_b.mtrl	✔	✔	✔	✔
	v01_c0101e0618_dwn_b_m.tex	✔	✔	✔	✔
	v01_c0101e0618_dwn_b_n.tex	✔	✔	✔	✔
	mt_c0101e0618_dwn_b.mtrl	✔	✔	✔	✔
	c0201e0618_dwn.mdl		✔	✔	✔	✔
	v01_c0101e6013_sho_b_m.tex	✔	✔	✔	✔
	v01_c0101e6013_sho_b_n.tex	✔	✔	✔	✔
	c0201e6013_sho.mdl		✔	✔	✔	✖
Missing File: chara/equipment/e6013/material/v0001/mt_c0101e6013_sho_b.mtrl
	Some files this mod references are missing or disabled.
	This may cause some variants of this model to be invisible in game.
	mt_c0101e0619_glv_b.mtrl	✔	✔	✔	✔
	v01_c0101e0619_glv_b_n.tex	✔	✔	✔	✔
	v01_c0101e0619_glv_b_m.tex	✔	✔	✔	✔
	mt_c0101e0619_glv_b.mtrl	✔	✔	✔	✔
	c0201e0619_glv.mdl		✔	✔	✔	✖
Missing File: chara/equipment/e0619/material/v0003/mt_c0101e0619_glv_b.mtrl
Missing File: chara/equipment/e0619/material/v0004/mt_c0101e0619_glv_b.mtrl
	Some files this mod references are missing or disabled.
	This may cause some variants of this model to be invisible in game.
Scanned 192 modded files.
	3 Warnings (May cause invisible items/models in game)

Checking LoD settings....
	FFXIV set to DX11 Mode	✔
	Per-DAT File Size Limit: 32.00 GB
	Sum Total Mod Files Size: 32.00 GB
	LodType_DX11 OFF	✔
`

I have tried start over:

![start over error](https://user-images.githubusercontent.com/8331186/107864227-b511d200-6e38-11eb-9df1-0ed2660b6e05.png)

I have tried rebuild cache too:

![Rebuild Cache Error](https://user-images.githubusercontent.com/8331186/107864245-09b54d00-6e39-11eb-8708-6e16eeb9c069.png)

**Comment by Squall-Leonhart** [comment]
Check again, because the Non negative/Count error is specifically tied to the index and dats being pre 5.4 when textools has been updated for the offsets of 5.4

attach a screenshot of the sqpack location with the file times showing.

**Comment by moahrs** [comment]
Sorry about this. I do not know, my FFXIV, some files was in drive E (main files), and anothers on drive D... I deleted files from drive D, and the game updated all files in E... man, that was stranger...

Whatever, thank you so much for you help, and you patient... 

Fixing my install, the problem solved... thank you

**Comment by Squall-Leonhart** [comment]
Steam can be weird at times!

Glad its fixed though :)
