### ISSUE TITLE
[Bug]: 'Add to Viewer' did not work

### ISSUE THREAD

**Issue by Apexciel** [TexTools/FFXIV_TexTools_UI#271]
### Expected behavior?

Generate facial features of my designated race

### Actual behavior?

Adding to the viewer remains the foundation

### Steps to reproduce the problem

Hello! I am currently using 2.3.8.4 and 2.3.8.5. After clicking on "Apply Deformed Shapes", the facial model in the viewer is still the basic facial model. I have tried all races and genders, but cannot save the applied shape deformations. Other body parts, clothing, weapons, etc. can be added normally. If this is not a software bug, please provide me with a brief answer, Thank you.

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Apply deformation shapes；Add to Viewer

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Lunaretic** [comment]
Unsure what cause of this was, but seems to be resolved or non-reproduce-able in current Dawntrail builds.
