### ISSUE TITLE
[Bug]: Hrothgar Hair 157 (Styled for Hire) unavailable for export as TTMP2 or Item Convert

### ISSUE THREAD

**Issue by Flannoit** [TexTools/FFXIV_TexTools_UI#274]
### Expected behavior?

I expected c1501h0157_hir to be exportable as either a TTMP2 or Item Convert

### Actual behavior?

c1501h0157_hir is completely unavailable for "Create Modpack" and "Item Convert" functions, despite otherwise existing in textools, being editable, etc. https://i.imgur.com/DgYqUAp.png

### Steps to reproduce the problem

1. Open TexTools
2. Go to "Character" → "Hair → "Hrothgar Male" → "Models" → "Number 157"
3. Confirm c1501h0157_hir exists
4. Go to either "Create Modpack" or "Item Converter"
5. Go to "Character" → "Hair" → "Hrothgar Male" → Attempt to find c1501h0157_hir/Hair 157
6. Find that c1501h0157_hir can't be exported as a ttmp2 or converted to a different item for some reason

### Error messages?

None

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Modpack Creator and Item Converter

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Flannoit** [comment]
Update: Just noticed c1501h0107_hir, c1501h0109_hir, c1501h0111_hir. c1501h0114_hir, c1501h0117_hir, c1501h0120_hir, v1501h0129_hir,  c1501h0162_hir, c1501h0164_hir, c1501h0166_hir, and c1501h0168_hir are also missing from Modpack Creator / Item Converter

**Comment by Squall-Leonhart** [comment]
Duplicate of https://github.com/TexTools/FFXIV_TexTools_UI/issues/252
