### ISSUE TITLE
[Bug]: Export/Import messing up normals on "AR-Caean Velvet Work Shirt of Crafting"

### ISSUE THREAD

**Issue by cnieuweboer** [TexTools/FFXIV_TexTools_UI#277]
### Expected behavior?

When exporting and importing a FBX or DB file. Without changing them (so no Blender involved), the model should look the same.

### Actual behavior?

![image](https://github.com/TexTools/FFXIV_TexTools_UI/assets/55538749/c04d8053-0590-417f-bf70-4e85d4080ca8)

For AR-Caean Velvet Work Shirt of Crafting (female hyur version) exporting and then importing messes up the normals on the chest.

### Steps to reproduce the problem

1. Export the "AR-Caean Velvet Work Shirt of Crafting" model as FBX or DB
2. Import "AR-Caean Velvet Work Shirt of Crafting"

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Model export/import

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Lunaretic** [comment]
This is likely caused by the vertices not being properly re-welded during tangent calculations.  Need to investigate to confirm and see exactly why.

**Comment by Lunaretic** [comment]
Can confirm this bug still exists.  Does not occur when just reading/writing the mdl back internally, but does occur with exporting/importing the FBX or other format file.  Definitely seems like probably an issue with the welding/binormal calculations.

**Comment by Lunaretic** [comment]
Upon further investigation, this is caused by Tangent/Binormal calculations being incorrect due to the different tris being in different parts of the same mesh group.  This does confirm that SE uses welded mesh groups when calculating the tangent data, which is good to know.  Fixing this is a somewhat large scope issue involving rewriting the tangent calculation stuff, so might not happen for a little bit

**Comment by Lunaretic** [comment]
This is resolved for next release with corrected tangent/binormal calculations.

**Comment by Lunaretic** [comment]
Correction, re-opening this.  The issue is greatly moderated/diminished with correct Per-Part binormal/tangent calculations, but we will need to full-weld the meshes for 100% accuracy still.

**Comment by Lunaretic** [comment]
Ok, solved for realsies now with the most recent releases (3.0.8.x)
