### ISSUE TITLE
[Bug]: I cannot access to body models

### ISSUE THREAD

**Issue by HarpocratesAion** [TexTools/FFXIV_TexTools_UI#278]
### Expected behavior?

When clicking on the body gear in question, it's supposed to go there and eventually choose the model

### Actual behavior?

Gives me 3 different error messages and automatically closes by just clicking any body gear in the Gear section

### Steps to reproduce the problem

1. Just going to any gear on the body section did the trick for me

### Error messages?

![Screenshot (1)](https://github.com/TexTools/FFXIV_TexTools_UI/assets/159695408/6a769184-bc5e-4e08-9235-a429f2059cd8)
![Screenshot (2)](https://github.com/TexTools/FFXIV_TexTools_UI/assets/159695408/176986dd-8a75-431d-be80-8c68810f9335)
![Screenshot (3)](https://github.com/TexTools/FFXIV_TexTools_UI/assets/159695408/13812695-3063-474d-afab-24b3c56b4655)

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

I was just trying to access body gear, just so I could get the model

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
Your gamedata being broken is not a bug of the application, this is a support type issue and is serviced on the discord.
