### ISSUE TITLE
Flashing on G-SYNC monitor when TexTools is in focus.

### ISSUE THREAD

**Issue by TheOddball** [TexTools/FFXIV_TexTools_UI#28]
If you have `fullscreen and windowed` G-SYNC enabled, when using TexTools, the monitor flashes very irratically because of a low framerate. Having an option in the settings to up the framerate of the program to 60 or higher fps would solve this issue.

The same issue in a different program for more context and/or explanation: https://github.com/microsoft/terminal/issues/649

**Comment by Squall-Leonhart** [comment]
Not a great deal can be done for this case, the driver doesn't support taking hints to disable Gsync from an applications end

You can use a tool such as nvidia profile inspector to configure the application state at the drivers side

https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector
