### ISSUE TITLE
[Feature request]: Standard Modpack Creation Problem: Allow Imports of Basic Modpacks

### ISSUE THREAD

**Issue by ghost** [TexTools/FFXIV_TexTools_UI#280]
### Request box

The option to import basic modpacks into Standard Modpack creation, as with Advanced Modpack creation.

### Reason box

There is currently a problem with the Standard Modpack creation option, wherein this option does not allow users to select files which are not visible in the dropdown menus, such as .avfx, .sklb, .pap, et cetera. This presents a challenge in that it prevents users from adding descriptions and websites to optionless mods that include these file types.

Permitting Basic Modpacks to be imported into Standard Modpacks as with Advanced Modpacks, would allow modders to add descriptions and websites to mods which use the file types but lack option toggles.

Alternatively, another solution would be adding the option to designate Advanced Modpacks as being single-choice, or to make the file formats mentioned visible during Standard Modpack creation, as they are with Basic Modpack creation.

I would be grateful if you would find a way to resolve this issue. If it's already implemented and I somehow missed it, please let me know how to go about this with the current TextTools version, as I'd really like to create modpacks with descriptions that use vfx. et cetera, but also don't have toggles for different options.

### Examples

N/A

**Comment by Lunaretic** [comment]
Standard modpacks are intended to be simple used case 'include all files used by item' stuff.  The Advanced modpack creator exists to solve the purposes you're requesting.  You can easily set up an advanced modpack with a single radio button/single select type group and add whatever files you want to it.  Please see the toggles at the top of the Advanced Modpack create group menu.
