### ISSUE TITLE
[Bug]: Textures not matching in-game ones

### ISSUE THREAD

**Issue by KitBallard64** [TexTools/FFXIV_TexTools_UI#294]
### Expected behavior?

![Untitled](https://github.com/TexTools/FFXIV_TexTools_UI/assets/19273132/793414af-0938-4e72-8219-53b33a2e7413)

### Actual behavior?

![image](https://github.com/TexTools/FFXIV_TexTools_UI/assets/19273132/fa3d06da-190b-4d5d-8fcd-eb151f215e98)

### Steps to reproduce the problem

Load TexTools
Goto ghost barque trousers of fending
Load the model

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: Model Viewer
Item: Ghost Barque Trousers of Fending, all versions (There's more but this one stands out)

I was building the outfit I made for my paladin and got to these pants and was confused at why the detailing is missing. I've noticed this on a few other items as well, but this one stands out the most. I am not using any mods (that should affect TexTools) and I've ran through some of the reset stuff under Help. I feel like I've done everything right so I figured I'd log it here as a bug. Sorry if it really isn't.

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
Textools is correct as far as the materials go, the chain skirt is pulled in from elsewhere.

**Comment by Lunaretic** [comment]
This is a will-not-fix.  The chain texture is from the sub-material, set by the colorset, which TT does not render for various reasons, mostly relating to it being expensive and complex.

If you're seeking to remove said chain texture, edit the tile material in the associated colorset row.

**Comment by KitBallard64** [comment]
I'm not looking to remove it, I'm looking to have the chain texture exported on the model to be used in Blender. At the moment it just exports it as plain as the preview image.
