### ISSUE TITLE
[Bug]: Error to import old and upgraded modpacks in TT3.0

### ISSUE THREAD

**Issue by WandererAether** [TexTools/FFXIV_TexTools_UI#296]
### Expected behavior?

Should Import Modpacks without issue.

### Actual behavior?

While trying to import old and upgraded modpacks to 3.0 version, I get a pop up with this message:

"The import has been cancelled due to an error:
Exception of type 'xivModdingFramework.Cache.CacheException' was thrown."

### Steps to reproduce the problem

1. Mods > Import Modpacks
2. Modpack selected (in that case there are 618 files in the pack)
3. Import Files
4. Error Message
5.
...

### Error messages?

The import has been cancelled due to an error:
Exception of type 'xivModdingFramework.Cache.CacheException' was thrown.

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)
618 items in total, mainly for Male Highlander, including gears (fet, hands body and pants), body parts and hair.

### Has this has been confirmed as an actual bug?

- [x] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Lunaretic** [comment]
Resolved
