### ISSUE TITLE
[Bug]: TexTools crash/not responding when using change destination option.

### ISSUE THREAD

**Issue by xinasphodel** [TexTools/FFXIV_TexTools_UI#298]
### Expected behavior?

Changing the destination of a mod install should complete and change intended files.

### Actual behavior?

When using the change destination feature on installing a mod, TexTools stops responding entirely. Happens even after using Start Over/Download Index.

### Steps to reproduce the problem

1. Import mod that has option to change destination.
2. Install steps according as usual.
3. When clicking Finish after choosing intended destination, TexTools immediately stops responding.

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: Importer on version 3.0.2.2 Worked as of version 3.0.1.6-.7

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
Fixed in 3.0.2.3
