### ISSUE TITLE
Why was Mod Conversion removed from TexTools?

### ISSUE THREAD

**Issue by Revent7** [TexTools/FFXIV_TexTools_UI#30]
Previously people were able to change the base of the mod if they did not like which item the mod creator had chosen to it but now that option is nowhere to be seen in the current version.

**Comment by Squall-Leonhart** [comment]
Look harder.

**Comment by Hysty** [comment]
I got the same question that I can't find where I can make a selection of the destination items on importing the mods.

**Comment by Squall-Leonhart** [comment]
> I got the same question that I can't find where I can make a selection of the destination items on importing the mods.

There is no such option.
