### ISSUE TITLE
[Bug]: color dye

### ISSUE THREAD

**Issue by anastasia1295** [TexTools/FFXIV_TexTools_UI#300]
### Expected behavior?

color wrong

### Actual behavior?

color not dyable

### Steps to reproduce the problem

1.dont know
2.
3.
4.
5.
...

### Error messages?

na

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)
problem after dawntrial

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
This bug report sounds more like needing support, which is provided on the discord.

Closing this because its not actionable in its present form
