### ISSUE TITLE
[Bug]: Male Viera don't have weight painting on face bones (Vanilla, unmodded)

### ISSUE THREAD

**Issue by InvaderCristi** [TexTools/FFXIV_TexTools_UI#302]
### Expected behavior?

The facial bones being weighted to the face

### Actual behavior?

The facial bones are not weighted https://cdn.discordapp.com/attachments/1127656033477742752/1260627101858660352/image.png?ex=669001fa&is=668eb07a&hm=96b238a332af22fc4bdbb7ee161356d9e0ac25157de23eceac848cd9f4e3c412&

### Steps to reproduce the problem

1. Export any male viera face
2. Check the bone weights
3. It isn't weighted, yippee!
4.
5.
...

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)
Full model viewer/export.

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
Delete the contents of the skeleteon folder and turn on the option to export full skeletons, we're not clearing the folder of 2.x skeletons because some users may have stored custom ones in there for their own workflows.
