### ISSUE TITLE
[Bug]: I lost all installed mods info when I reinstall a new version textools

### ISSUE THREAD

**Issue by FredYakumo** [TexTools/FFXIV_TexTools_UI#306]
### Expected behavior?

When install a new version of ffxiv tex tools, should not lost any installed info.

### Actual behavior?

I was used an older version texTools, when I install a new version of textools, I lost all installed mods info, but game's data is stilled modified. And when I try to install a new mod, failed with game index data problem.

### Steps to reproduce the problem

1. install old version
2. install some mods
3. install a new version tex tools, and path is same with the old one
4. Open managed mod lists, can't see any installed mod

### Error messages?

---------------------------
Non-Dawntrail Install
---------------------------
TexTools is currently assigned to a Endwalker or previous install.

Many parts of the application will not operate correctly on old FFXIV installs.
---------------------------
OK   
---------------------------

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Lunaretic** [comment]
This is known behavior and will not change, when upgrading from 2.x, and is why there are gigantic warning messages currently on every patch note, as such:

DO NOT INSTALL THIS UPDATE IF YOUR REGION DOES NOT HAVE THE DAWNTRAIL EXPANSION
如果你所在的地区没有《黎明轨迹》扩展包，请不要安装此更新
해당 지역에 DAWNTRAIL 확장팩이 없는 경우 이 업데이트를 설치하지 마십시오.

**Comment by FredYakumo** [comment]
> This is known behavior and will not change, when upgrading from 2.x, and is why there are gigantic warning messages currently on every patch note, as such:
> 
> DO NOT INSTALL THIS UPDATE IF YOUR REGION DOES NOT HAVE THE DAWNTRAIL EXPANSION 如果你所在的地区没有《黎明轨迹》扩展包，请不要安装此更新 해당 지역에 DAWNTRAIL 확장팩이 없는 경우 이 업데이트를 설치하지 마십시오.

Alright, I understand. But may I ask if there is a way for me to restore the version of textools I previously installed and obtain information about the mods I had installed?
