### ISSUE TITLE
[Bug]: Export error

### ISSUE THREAD

**Issue by Katenkiokotsu** [TexTools/FFXIV_TexTools_UI#307]
### Expected behavior?

it was suppoused to export a model with a .fbx file

### Actual behavior?

it failed to export a model and close

### Steps to reproduce the problem

1.created a female Miqo'te
2.seleceted tantra armor set
3.selected opal earrings of slaying
4.select tail 
5.click export and error ocurred
...

### Error messages?

![image](https://github.com/user-attachments/assets/94fcb5c8-703d-47df-ae1b-967d70466a1c)

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)
![image](https://github.com/user-attachments/assets/5c011d7c-97bc-419c-beca-cc3d4dcdba50)
![image](https://github.com/user-attachments/assets/ddce09d3-c5a7-4fff-9edd-dc2f8f6a0dbf)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Katenkiokotsu** [comment]
I didn't want to mark it as a confirmed bug but it would not let me post it anyother way.

**Comment by Squall-Leonhart** [comment]
Confirmed

**Comment by Squall-Leonhart** [comment]
Narrowed it down to the miqote skeleton.

**Comment by Katenkiokotsu** [comment]
> Narrowed it down to the miqote skeleton.

So i should try creating another race?

**Comment by Squall-Leonhart** [comment]
seems it only exports with Au Ra F

**Comment by Katenkiokotsu** [comment]
little update, i dowloaded the previous version V3.0.8.1 and it works fine in the previous version

**Comment by Lunaretic** [comment]
Fixed in next version (3.0.8.3)
