### ISSUE TITLE
[Bug]: Missing vertex groups in exported FBX after updating system install

### ISSUE THREAD

**Issue by Baplar** [TexTools/FFXIV_TexTools_UI#312]
### Expected behavior?

Until recently, the exported FBX models generated by my system install of TexTools contained all vertex groups, especially in the face models, allowing for controlling all parts of the face by posing all the bones.
![image](https://github.com/user-attachments/assets/586a2456-f7cd-4dd5-a9f5-3623d400a11a)
I just re-tested it by downloading version v3.0.8.4, it works as intended.

### Actual behavior?

After updaing to version v3.0.8.5, only a handful of vertex groups are exported. Because of this, most bones no longer affect the movement of the vertices that they should correspond to, resulting in broken animations.
![image](https://github.com/user-attachments/assets/a8b16d33-a3cc-4fcb-8582-d1dd86d3e062)

### Steps to reproduce the problem

*Note: the following only happened on a system install, this may not be reproducible everywhere.*

1. Select a model to export (in my case, I tried Elezen Male Face 2)
2. Save model as FBX
3. Open Blender (tested both versions 2.83 and 4.2) and import the FBX
4. Select the mesh in the outliner, and consult its object data properties -> Vertex Groups
    - Only a small subset of the expected vertex groups are present
5. Enter Pose Mode, and try to move or rotate some bones (in my case, I tried the head bone i.e. j_kao)
    - Some parts of the mesh do not move as they should
![image](https://github.com/user-attachments/assets/3e288fc2-3a69-4116-a9fc-34b610f33d11)

### Error messages?

No error or warning suggesting that something went wrong during the export

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: FBX exporter (I have no idea if the problem is in the exporter itself or further up the pipeline)
Item: Elezen Male Face 2

### Workaround

Uninstalling and reinstalling seemed to solve the issue.
Running the portable zip build also works.

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Baplar** [comment]
After checking further, v3.0.8.4 seems to have a different issue, with the bone hierarchy being partly flattened. This was probably addressed in v3.0.8.5, with the side effect described in this issue.

**Comment by Baplar** [comment]
After yet further testing, the portable version of 3.0.8.5 seems fine...!

So it might be related to some old settings in my installed instance, maybe an update did not clean something?
I’ll try uninstalling and reinstalling 3.0.8.5 from scratch, and see if this starts working again.

**Comment by Baplar** [comment]
Okay, uninstalling and reinstalling from scratch solved the issue.

Should I close this ticket, or leave it open to investigate why an upgrade may have caused this to happen?

**Comment by Squall-Leonhart** [comment]
it happened because the skeletons folder had old skels in it and/or export full skeletons was unchecked.
