### ISSUE TITLE
[Bug]: Missing Skeleton

### ISSUE THREAD

**Issue by LadyJ9** [TexTools/FFXIV_TexTools_UI#325]
### Expected behavior?

Building the FFXIV FBX model and exporting.

### Actual behavior?

When I set up the female Aura head, I try using other clothing and almost none of them work. The skeleton was set to female aura when I got the head into the FMV. I have only found 2 pieces of clothing that worked so far but any other makes the body too big.

### Steps to reproduce the problem

1. Selected female Aura Face 4
2. View it in Full Model Viewer
3. Selected Gaia's Attire
4. The body ends up becoming big
5. Regenerated skeletons to try and fix the issue
6. A small window pops up saying I was missing a .XML file
![image](https://github.com/user-attachments/assets/6e5a088b-62af-4e98-8c22-41985034d50c)
![image2](https://github.com/user-attachments/assets/3285b73d-c137-4fe2-a8a6-5bf042f606fe)

### Error messages?

Failed to regenerate one or more skeletons:
Could not find file '![image](https://github.com/user-attachments/assets/47c5cd1e-9dda-4edf-802b-5e6aef678284)c0101b0001.xml'.

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: Full Model Viewer
Item: Female Aura face, hair, and tail. Gaia's attire

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
This is caused by your windows user account permissions or missing runtime, not a bug.
