### ISSUE TITLE
Error(s) when loading a backup of mods after trying out new mods.

### ISSUE THREAD

**Issue by Noble333** [TexTools/FFXIV_TexTools_UI#36]
![Firefox_Screenshot_2021-03-12T11-22-21 792Z](https://user-images.githubusercontent.com/80520935/110934266-a2c56f80-82e2-11eb-9b6a-ea4bdd5361c3.png)
[TexTools FFXIV errors (3-13-2021).txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/6129574/TexTools.FFXIV.errors.3-13-2021.txt)

Attached is a copy of the error messages I received, which I've never seen before in all the time I've used TexTools. I tried out a body mod temporarily, so before I did that, I saved all my mods (I have/had a lot of them) and used a very long name for the modpack to make it easily identifiable from numerous backups before this one in particular. After seeing that it wasn't for me, I chose to Start Over and then went to reload my saved Modpack -- which saved without any issues beforehand. Then I get this extremely long list of errors, which I don't understand.

**Comment by Lunaretic** [comment]
Most likely you have broken index files.  Use the Download Index Backups button before starting over.
