### ISSUE TITLE
Final Fantasy 14 not being supported by this version of TexTools 2.3.4.21

### ISSUE THREAD

**Issue by Naomi-lightbearer** [TexTools/FFXIV_TexTools_UI#38]
![image](https://user-images.githubusercontent.com/67130744/111777890-ccb2ff00-88ab-11eb-89e2-8b8c58c050ec.png)

i dont know what to do honestly, i tried downloading index (didnt work) tried to use "Start Over" (said use "Check for problems") then i went to try for problems and it said everything was running fine but when i logged into the game none of my mods were working...

![image](https://user-images.githubusercontent.com/67130744/111786689-fc670480-88b5-11eb-9872-f2eee5c60917.png)

**Comment by snepaii** [comment]
Did you ever find a solution for this? I just got this today after patch 7.2 and i have no idea what to do about it.
