### ISSUE TITLE
Nameless I/O disk error 

### ISSUE THREAD

**Issue by ghastimafrix** [TexTools/FFXIV_TexTools_UI#39]
Hello there! I dropped a message regarding this issue in the discord, but I figured it would be worthwhile to make a thread here with the error messages too. So, long story short;
Since early this afternoon I've been experiencing a bug out of nowhere, after enabling a mod downloaded off the archive, and the only message I get when trying to import a modpack, reset the cache, or start over entirely is this;

![image](https://user-images.githubusercontent.com/81707803/113188736-6c677a00-9228-11eb-948a-41d2b9197ef7.png)

I also happened to crash while poking around, and these messages were displayed to me in sequence;
![image](https://user-images.githubusercontent.com/81707803/113189111-d5e78880-9228-11eb-8472-29ec72b4dbd6.png)
![image](https://user-images.githubusercontent.com/81707803/113189158-e3047780-9228-11eb-9aac-83820ceea464.png)
![image](https://user-images.githubusercontent.com/81707803/113189273-00d1dc80-9229-11eb-91d6-1bc717018a5a.png)

Problem Checking results in this;
![image](https://user-images.githubusercontent.com/81707803/113189562-527a6700-9229-11eb-9065-84cb64297b7c.png)

I wasn't able to find a fix or solution anywhere online.  Like anyone with half a brain, I have already uninstalled/reinstalled the program, done a complete purge, ensured that the wizard was looking for the game in the right directory, etcetera. I wouldn't be filing a report if I hadn't exhausted all other options. 
Frankly I'm just confused, because I wasn't having any issues at all until now.

**Comment by Corrodias** [comment]
A disk I/O error is a bad sign. It almost certainly means a hardware failure. Maybe it's a bad sector on the disk. You should do a run of chkdsk with surface scan enabled, but make sure you have everything backed up that's important first, because the increased activity only makes it more likely to fail further.
