### ISSUE TITLE
[Feature Request] Add the ability to select multiple elements in the mod list

### ISSUE THREAD

**Issue by BSoD38** [TexTools/FFXIV_TexTools_UI#40]
Hi, I've just encountered a situation where this feature would've been very useful.

I've installed the HD icon pack plugin and several other mods, and needed to make a backup modpack for an update. Creating a backup modpack doesn't keep the original modpack structure, which means I can only delete/disable mods on a per-file basis. I now want to delete the HD Icon Pack to prepare for the 5.5 patch, but I can't do this easily as this mod is comprised of thousands of unique files since the modpack structure is lost.

It would've been super useful if I could select all of the files in the UI section with shift+left click, and batch delete all of the selected files.

**Comment by Lunaretic** [comment]
This was added at some point, should've been closed.
