### ISSUE TITLE
Penumbra "Redirect imports to Lumina" Option Addition

### ISSUE THREAD

**Issue by KhaozFrost** [TexTools/FFXIV_TexTools_UI#50]
I'm wondering If its possible if this option is checked since Its not going to overwrite files the way textools does and instead import them thru Lumina ways if it be possible to not have to close out of the game (you know the "please exit before yada yada" popup. This would allow us to be more selective on what parts of mods we want to install while utilizing this new feature to its full potential.

**Comment by Lunaretic** [comment]
TTMP installs are not supported in lumina mode.  (They do not work correctly and were supposed to be disabled last patch).  Use the TTMP installer built into Penumbra.
