### ISSUE TITLE
Allow backup to preserve original metadata of installed mods

### ISSUE THREAD

**Issue by icy-** [TexTools/FFXIV_TexTools_UI#53]
(feature request) Hi, came across an issue recently where backups removed metadata (mod authors, names, etc) at the time of backup.  I took a look at the generated mpl file and it's filled with many lines of _Backup Name_ and author _TexTools User_ (or whatever is set).

Related feature request would be, at backup import time, to keep all mods separate instead of under the _Backup Name_/_TexTools User_ umbrella.   If the metadata is preserved, there might be a way to write the .mpl file to also import as a bunch of separate packages, too.

currently an import reduces individual mod enable/disable flexibility:
![](https://cdn.discordapp.com/attachments/802338126940340225/834905177060278344/unknown.png)

thanks!

**Comment by Lunaretic** [comment]
This is already scheduled under a different issue.
