### ISSUE TITLE
Viewing of loading screens no longer available.

### ISSUE THREAD

**Issue by captice** [TexTools/FFXIV_TexTools_UI#57]
Loading screens can not be viewed or exported since Patch 5.5 and TexTools Version 2.3.4.23 to current version 2.3.5.8.
![image](https://user-images.githubusercontent.com/44450786/116787666-c473f380-aae8-11eb-876f-443dcf1adcb1.png)

**Comment by KoraLyn** [comment]
Fixed with 2.3.5.10
