### ISSUE TITLE
Ability to disable/enable multiple selectable mods at once

### ISSUE THREAD

**Issue by Kussie** [TexTools/FFXIV_TexTools_UI#58]
It would be nice to be able to select multiple mods in the mod list at once and perform a batch enable/disable on only those selected. 

Would make life easier when debugging mods or adding a new mod that might have impacts on a previously installed mod and avoid having to reinstall a bunch of mods afterwards

**Comment by Lunaretic** [comment]
This is already covered by another issue here 
https://github.com/TexTools/FFXIV_TexTools_UI/issues/40
