### ISSUE TITLE
The mod paintings are not displayed in games

### ISSUE THREAD

**Issue by Luna664** [TexTools/FFXIV_TexTools_UI#60]
![FFXIV_TexTools_DEXZ55Im79](https://user-images.githubusercontent.com/75101727/117523980-8fb9dd80-afbb-11eb-997c-3b9c40dfe9a1.png)

![ffxiv_dx11_HApbJCeUHg](https://user-images.githubusercontent.com/75101727/117523983-934d6480-afbb-11eb-9e9b-94f85dc8719d.jpg)

**Comment by Lunaretic** [comment]
This is caused by the paintings listed in TexTools actually being the ones that show up in the menus apparently, not the furnishing usage.  Unsure where theses textures come from currently.

**Comment by Lunaretic** [comment]
Resolved.  The In-Game versions of the paintings are now visible/editable in TexTools.  Unfortunately we don't have the real human readable names for them, since the IDs don't match up with the UI versions, but nothing to be done about that one.
