### ISSUE TITLE
Eqp offset issue?

### ISSUE THREAD

**Issue by atlas-web** [TexTools/FFXIV_TexTools_UI#61]
After updating, it will no longer let me install natis mani pedi megapack which fixes all hands and feet in game. Ive tried uninstalling, completely starting over,  installing old versions etc etc. nothing seems to fix this issue. It keeps saying something about an issue with equipment offset and installs nothing. ive been able to pick and choose 1 or 2 things and it installs just those fine, but if i select a bunch or even a handful it gives me this error and installs nothing. whats the cause/fix for this?

**Comment by atlas-web** [comment]
it looks like the issue is with the metadata files? If i manually go through and deselect all the metadata files it installs it just wont install with any of the metadata files checked. the problem is in game it causes a large majority of characters legs to disappear

**Comment by Lunaretic** [comment]
Hmm. Not able to replicate on my end, but that sounds more like an issue with your indexes/dats being corrupt in some fashion.

**Comment by KoraLyn** [comment]
Closing this as it has probably been resolved by now and likely isn't a bug.
