### ISSUE TITLE
Once opened, the installation location is expired

### ISSUE THREAD

**Issue by a15978978679** [TexTools/FFXIV_TexTools_UI#66]
![image](https://user-images.githubusercontent.com/86378094/123155100-41449d80-d49a-11eb-9b82-37db6ed6b48c.png)

**Comment by jckling** [comment]
你好，如果是在我的博客上评论的朋友，我已经回复你啦~

貌似是启动之后要定位这个目录（？

比如我把游戏安装在了 D 盘，那么这个目录就是：

```
D:\Program Files (x86)\FFXIV\最终幻想XIV\game\sqpack\ffxiv
```

**Comment by KoraLyn** [comment]
I'm going to assume by the lack of a reply that this issue has been resolved. If not, you can re-open the issue.
