### ISSUE TITLE
Off-hand only not displayed correctly (missing glow/disappear when sheathed)

### ISSUE THREAD

**Issue by Aakkvv** [TexTools/FFXIV_TexTools_UI#77]
Used item conversion to copy Sphairai Ultima onto another item. Glow only works on main hand, not on off-hand. 
Also used item conversion to copy Ultimate Vorpal sword and the off-hand disappears when weapon is sheathed.

**Comment by Lunaretic** [comment]
Unsure if this is fixed or not currently.  IMC handling for Offhand models is very dubious in general since SE is all over the place on if the offhand uses an IMC file or not, with no discernible way to tell.

**Comment by Lunaretic** [comment]
This should be resolved now with the recent IMC correction updates for dual wield things.
