### ISSUE TITLE
ffxiv cn patch 5.5 issue

### ISSUE THREAD

**Issue by Belialu** [TexTools/FFXIV_TexTools_UI#78]
An error occurred while attempting to rebuild the cache. This may be caused by this version of Final Fantasy XIV not being supported by this version of TexTools.

Non-negative number required.
Parameter name: count
an when i tried to download the missing index it shows
Could not find file 'D:\Program Files (x86)\FFXIV TexTools\FFXIV_TexTools\NONE'.

**Comment by Squall-Leonhart** [comment]
Chinese service players can use this dev build to solve this 
https://cdn.discordapp.com/attachments/368482175051366410/874579721797644288/FFXIV_TexTools_v2.3.6.2_dev.zip

**Comment by Squall-Leonhart** [comment]
Use this one, last one was missing a change.
https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip

**Comment by Belialu** [comment]
it's solved! thx very much!
