### ISSUE TITLE
FFXIV_TexTools_v2.3.6.2

### ISSUE THREAD

**Issue by ophesw** [TexTools/FFXIV_TexTools_UI#82]
v2.3.6.2couldn't show and export chest

**Comment by Squall-Leonhart** [comment]
> v2.3.6.2couldn't show and export chest

Chinese client?

**Comment by ophesw** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TexTools/FFXIV_TexTools_UI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TexTools/FFXIV_TexTools_UI] FFXIV_TexTools_v2.3.6.2 (#82)





  
v2.3.6.2couldn't show and export chest
  
Chinese client?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Squall-Leonhart** [comment]
Please try with this one

https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip

**Comment by ophesw** [comment]
OK，I'll try it. thanks
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TexTools/FFXIV_TexTools_UI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 中午11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TexTools/FFXIV_TexTools_UI] FFXIV_TexTools_v2.3.6.2 (#82)





 
Please try with this one
 
https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ophesw** [comment]
It couldn't work.
when i chose chest,it show me this pic





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TexTools/FFXIV_TexTools_UI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 中午11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TexTools/FFXIV_TexTools_UI] FFXIV_TexTools_v2.3.6.2 (#82)





 
Please try with this one
 
https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Squall-Leonhart** [comment]
ok, if neither of them work you most likely have bad indexes and possibly even data file errors.

Can you ask friends if they keep up to date clean backups and obtain replacements from them?.

**Comment by ophesw** [comment]
maybe i should redownload it,i'll try


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TexTools/FFXIV_TexTools_UI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 中午11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TexTools/FFXIV_TexTools_UI] FFXIV_TexTools_v2.3.6.2 (#82)





 
ok, if neither of them work you most likely have bad indexes and possibly even data file errors.
 
Can you ask friends if they keep up to date clean backups and obtain replacements from them?.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ophesw** [comment]
thx！i rebuild the data,now i coulde export chest!thx a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TexTools/FFXIV_TexTools_UI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 中午11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TexTools/FFXIV_TexTools_UI] FFXIV_TexTools_v2.3.6.2 (#82)





 
ok, if neither of them work you most likely have bad indexes and possibly even data file errors.
 
Can you ask friends if they keep up to date clean backups and obtain replacements from them?.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
