### ISSUE TITLE
Bows animation sideways

### ISSUE THREAD

**Issue by YungGodChris** [TexTools/FFXIV_TexTools_UI#83]
When using the item converter on a bow it seems that if you use an animated bow the bows animations are sideways and your spells shoot out of the top of the bow
![ffxiv_08152021_194104_977](https://user-images.githubusercontent.com/29798207/129504403-86185137-4d99-4ba8-b2c7-1ecd563b2351.png)

**Comment by Lunaretic** [comment]
Not a TexTools bug/will not fix.  FFXIV Weapon skeletons are not all oriented the same way.
