### ISSUE TITLE
bugged Textures and Clashing mods 

### ISSUE THREAD

**Issue by SkyeSunfire** [TexTools/FFXIV_TexTools_UI#85]
I installed a mod that takes the tattoo off the Craftsman's signet and now I have no torso, also the valentino suit I installed the rolled sleeves now they don't even show being rolled up. I wiped Textools clean and ran a system check too see if everything was ok and its was not and i have no idea how to fix it

**Comment by Squall-Leonhart** [comment]
not a bug

**Comment by KoraLyn** [comment]
Please refer to the TexTools Discord help channels for help with mods.
