### ISSUE TITLE
Crash when opening TT

### ISSUE THREAD

**Issue by nightsart** [TexTools/FFXIV_TexTools_UI#86]
After some time of not opening TT, since I use Penumbra, I was greeted by simply nothing. When checking tasks manager, I observed it would get interrupted and disappear until I tried again. I tried reinstalling it, and now this is what I get:
[message.txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/7023237/message.txt)
[message (1).txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/7023235/message.1.txt)
[message (2).txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/7023236/message.2.txt)
It has happened to me once before back when I wasn't using Penumbra, I believe. I am not sure how I solved it, but I know I spent the entire day restarting my laptop and reinstalling TT.

**Comment by Squall-Leonhart** [comment]
navigate to the folder indicated in the log and delete the xml, its been zero filled

**Comment by nightsart** [comment]
Thank you so much it works well again 😄
