### ISSUE TITLE
TexTools doesn't open anymore

### ISSUE THREAD

**Issue by ThePotato1** [TexTools/FFXIV_TexTools_UI#87]
Pretty much at loss on what to do with this. I had some mods installed before a 2 weeks ago and was working fine. Did an update for it and doesn't open anymore.
[Error1.txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/7040362/Error1.txt)
[Error2.txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/7040363/Error2.txt)

**Comment by Pastelle0** [comment]
Same ive been having issues wit the program finding ffxivgame.ver i can start over i cant get index back ups it constantly tells me Error:Object Reference not set to an instance of an object.

**Comment by Squall-Leonhart** [comment]
Issues is not a support forum, use the discord.
