### ISSUE TITLE
unable to load texture file

### ISSUE THREAD

**Issue by SayuriHagami** [TexTools/FFXIV_TexTools_UI#89]
![FFXIV_TexTools_hQkp3cFVsl](https://user-images.githubusercontent.com/89530470/130805725-2b912808-9d5b-4c3c-9a5d-7e984e9f1dcc.png)

Only for AuRa female face 1 this problem pops up. I reinstalled TexTool around 10 times after deinstalling and even if I had no mods on it keeps showing this problem.

**Comment by Squall-Leonhart** [comment]
Not a textools issue, reset your indexes with default/clean.
