### ISSUE TITLE
bricked by choosing wrong directory on first start

### ISSUE THREAD

**Issue by nuneze54** [TexTools/FFXIV_TexTools_UI#90]
If you choose the wrong directory on first launch, you break the tool. It just starts with "Critical Index Error: A critical error occurred when attempting to read the FFXIV index files. Would you like to restore your index backups?"
Choosing either yes or no just closes the tool, re-installing doesn't help.

**Comment by Squall-Leonhart** [comment]
Selecting an outdated location or location where files have been incompletely deleted is user error.

**Comment by nuneze54** [comment]
So I can never use this tool again because of an error I made?! Wow...

**Comment by Squall-Leonhart** [comment]
you can clean up and delete or move the incorrect folder you selected and you will be prompted to select the right one.

Textools will only be offering to restore indexes in a location that is a subdirectory of game\sqpack\ when criteria such as the presence of game\ffxivgame.ver being met.

**Comment by Squall-Leonhart** [comment]
Infact, the criteria for this error is that 0a0000.win32.index is missing from the /ffxiv/ folder you selected, so correcting your mistake is as simple as navigating to the location the file is missing from and renaming or deleting [ffxiv] itself

**Comment by nuneze54** [comment]
Well, then this is not working because I've chosen the Endwalker benchmark folder on my desktop. I deleted it some time ago, but I still cannot run TexTools.

**Comment by Squall-Leonhart** [comment]
Then time to kill %localappdata%\FFXIV_TexTools
