### ISSUE TITLE
viera faces 101-104 unmoddable 

### ISSUE THREAD

**Issue by maknaeline** [TexTools/FFXIV_TexTools_UI#91]
![](https://i.gyazo.com/5bef5aaa00cee01506ae7bce9441ad86.png)

**Comment by Squall-Leonhart** [comment]
The FACs are shared, thats why they do not appear here.

**Comment by KoraLyn** [comment]
As mentioned, a lot of the face assets are shared by both Veena and Rava so this .mtrl actually just doesn't exist.
