### ISSUE TITLE
BUG report：The TexTools2.3.6.2 has serious problems on the Chinese version of FFXIV

### ISSUE THREAD

**Issue by Doc-CHeale** [TexTools/FFXIV_TexTools_UI#92]

**Comment by Doc-CHeale** [comment]
When Chinese users use the stable OR dev textools 2.3.6.2. If the size of mod reaches a certain number (about 4GB),they may not be able to import any new mod package (including manually changing maps or FBX), and the same problem will occur when deleting some metadata，here is the [error](https://cdn.discordapp.com/attachments/756450362919223377/882909947577372672/unknown.png)

**Comment by Squall-Leonhart** [comment]
There has been no corroborating issue reports to support the claims in this bug report, you need a reinstall i think.

**Comment by Type-2020** [comment]
I got the exact same issue here.

**Comment by KoraLyn** [comment]
TexTools limits the maximum amount of data you can import based on the file system that FFXIV is installed on. It is set to 4 GiB if your drive's file system is FAT32 in which case it is the maximum file size for that format.
