### ISSUE TITLE
Editing anything under UI/Online Status/* does not take effect ingame

### ISSUE THREAD

**Issue by JCmAxohtwEoK0fdaQip7** [TexTools/FFXIV_TexTools_UI#93]
Version: FFXIV TexTools 2.3.6.2

While the TexTools preview display correctly shows texture edits as you import them, it does not actually take effect in-game and is completely ignored. 

Examples with pre-existing mods that no longer work:
[NieR: Automata - Online Status Icons] https://www.xivmodarchive.com/modid/5493
[ERP Status] https://www.xivmodarchive.com/modid/1882
[Eggplant Mentor Icon] https://www.xivmodarchive.com/modid/412

**Comment by Squall-Leonhart** [comment]
This is not a  bug, you've turned on the 4k UI which none of these mods touch.
