### ISSUE TITLE
Yesterday, The Korean server has been updated to version 5.5. 

### ISSUE THREAD

**Issue by AnShirley322** [TexTools/FFXIV_TexTools_UI#96]
As a result, various errors are occurring.

This is an error when rebuilding first.

" An error occurred while attempting to rebuild the cache. This may be caused by this version of Final Fantasy XIV not being supported by this version of TexTools.

An item with the same key has already been added.
"

" An error occurred while attempting to rebuild the cache. This may be caused by this version of Final Fantasy XIV not being supported by this version of TexTools.

음수가 아닌 숫자여야 합니다.
매개 변수 이름: count 

(It has to be a number, not a negative number.
Parameter name: count)
"

I think it is necessary to update the response of the Korean server. Existing users can use the backup mode pack, but they cannot install a new mode.

Or if it's my personal problem, please help me!

**Comment by Squall-Leonhart** [comment]
offset changes have been made in this build
https://cdn.discordapp.com/attachments/472796287612485662/887352103939489862/FFXIV_TexTools_dev.zip

**Comment by KoraLyn** [comment]
This should be fixed in the next update, feel free to re-open if not.
