### ISSUE TITLE
Unable to perform any actions on mods

### ISSUE THREAD

**Issue by Type-2020** [TexTools/FFXIV_TexTools_UI#99]
I was trying to port TF3 heels from woolen dress shoes to housemaid's pumps and this notice pumps up. From then I can't install or uninstall any mods, neither can I port or do anything else

![](https://cdn.discordapp.com/attachments/867698882702737419/893156350157275186/unknown.png)
.

**Comment by Squall-Leonhart** [comment]
Issues is not a support desk, please use the textools discord.

**Comment by KoraLyn** [comment]
https://github.com/TexTools/FFXIV_TexTools_UI/issues/92#issuecomment-986228938

As explained here there is a hard limit to the amount of data you can import through TexTools.
